### ISSUE TITLE
Report results are counted incorrectly if Scenario Outline is present 

### ISSUE THREAD

**Issue by seaman1** [damianszczepanik/cucumber-reporting-jenkins#102]
Actual behaviour:
Scenario Outline is counted in report results table (see screen shot) as 1 scenario.
 
Expected behaviour:
Scenario Outline should be counted as multiple scenario in report table since it's a group of scenarios that is executed with different input data.

Additional info:
1. Plugin report results differs from cucumber console summary results. 
Console summary results:
```
88 scenarios (16 failed, 1 undefined, 71 passed)
489 steps (14 failed, 49 skipped, 1 undefined, 425 passed)
```
Plugin results: see screenshot.
2. Plugin report results differs from native cucumber html report (which duplicates console output results).

![report_summary](https://cloud.githubusercontent.com/assets/7382031/3512330/3d9e50e8-06b8-11e4-80df-5540a044bde5.png)

**Comment by damianszczepanik** [comment]
Let me know if you can reproduce this problem with new version
