### ISSUE TITLE
Report results are counted incorrectly if Feature Background scenario failes

### ISSUE THREAD

**Issue by seaman1** [damianszczepanik/cucumber-reporting-jenkins#104]
Steps to reproduce:
1. Make Feature Background scenario fail (Feature Background scenario is scenario which is executed as a first step inside every scenario in feature). Feature structure:
```
Feature: Volumes
...
  Background:
    Given I login and navigate to Volumes page

  Scenario 1
  ...

  Scenario 2
  ...
```
2. See jenkins-cucumber-jvm-report

Actual result:
Summary table shows that all scenarios passed (see screenshot).
By fact and due to console output all scenarios failed.
Looks like all failed scenarios are counted as "skipped" in steps column.
![jvm_results](https://cloud.githubusercontent.com/assets/7382031/3659669/d63cbb9e-11af-11e4-92e6-640ed98987e3.png)

Expected result:
All scenarios should counted as failed.

**Comment by wolff123** [comment]
is this defect going to be fixed soon?

**Comment by damianszczepanik** [comment]
Can you attach json file?

**Comment by damianszczepanik** [comment]
Support for background has been withdrawn in last release so this should not happen any more.
