### ISSUE TITLE
[Feature Request] Don't make publishing of reports cause Jenkins Job to fail (option in jenkins)

### ISSUE THREAD

**Issue by JasonSmiley** [damianszczepanik/cucumber-reporting-jenkins#105]
Right now I use a rake task to kick off test scripts.

The task runs my tests, and then re-runs all failed tests to make sure they are legit bugs (code pushes can cause tests to break because services are down during push).

Right now I am generating two JSON reports, one with an error, and one without.

I believe the cucumber report is finding the Failure in the initial JSON and marking the job as failed even though in this case I want it to pass.

**Comment by damianszczepanik** [comment]
https://github.com/damianszczepanik/cucumber-reporting-jenkins/wiki/Detailed-Configuration
