### ISSUE TITLE
Report are empty :-(

### ISSUE THREAD

**Issue by sassyn** [damianszczepanik/cucumber-reporting-jenkins#106]
Hi,

This one seems so cool, but I can't manage to run it.

The test is running under jenkins (see below) but the report is empty.
What do I miss?

cucumber profile: default 
directory: backoffice
$ bash -c "source /var/lib/jenkins/.rvm/scripts/rvm && cd /home/workspace/backoffice && rvm use ruby ruby-2.1.2 && bundle --quiet && bundle exec cucumber -p default  -c no_proxy=127.0.0.1 browser=chrome  --no-color"
Using /var/lib/jenkins/.rvm/gems/ruby-2.1.2
Using the default profile...
Feature: Billing
  ethoos billing

  Scenario: Good Billing api call                                                                                                             # features/billing/billing.feature:4
    Given I have customer named "Demo Customer" with email "demo.customer@gmail.com"                                                          # features/step_definitions/billing_steps.rb:1
    And I have application  "Ethoos" with plan "Platium" and price 234                                                                        # features/step_definitions/billing_steps.rb:34
    And the Log file is empty                                                                                                                 # features/step_definitions/billing_steps.rb:5
    When I call the billing api with "cmd=purchase&package=Platinum&user=Demo%20Customer&email=demo.customer@gmail.com&app=Ethoos&price=2343" # features/step_definitions/billing_steps.rb:10
    Then I should have 0 log entries                                                                                                          # features/step_definitions/billing_steps.rb:15
    And I should have a Purchase with amount 2343                                                                                             # features/step_definitions/billing_steps.rb:19

  Scenario: Bad Billing api call - wrong customer                                                                                             # features/billing/billing.feature:13
    Given I have customer named "Some Customer" with email "some.customer@gmail.com"                                                          # features/step_definitions/billing_steps.rb:1
    And I have application  "Ethoos" with plan "Platium" and price 234                                                                        # features/step_definitions/billing_steps.rb:34
    And the Log file is empty                                                                                                                 # features/step_definitions/billing_steps.rb:5
    When I call the billing api with "cmd=purchase&package=Platinum&user=Demo%20Customer&email=demo.customer@gmail.com&app=Ethoos&price=2343" # features/step_definitions/billing_steps.rb:10
    Then I should have 1 log entries with message "Customer not found, created customer"                                                      # features/step_definitions/billing_steps.rb:25
    And I should have a 0 Purchases                                                                                                           # features/step_definitions/billing_steps.rb:30

Feature: Login Features
  User Login

  Scenario: Succesfull Login                               # features/ui/login.feature:5
    Given I am User "admin@example.com"                    # features/step_definitions/ui_steps.rb:1
    And I am a regular user                                # features/step_definitions/ui_steps.rb:5
    And I am an admin user                                 # features/step_definitions/ui_steps.rb:10
    When I login with "admin@example.com" , "password123!" # features/step_definitions/ui_steps.rb:34
    Then I should be on the dashboard                      # features/step_definitions/ui_steps.rb:23

  Scenario: UnSuccesfull Login                            # features/ui/login.feature:12
    Given I am User "admin@example.com"                   # features/step_definitions/ui_steps.rb:1
    And I am an admin user                                # features/step_definitions/ui_steps.rb:10
    When I login with "admin@example.com" , "badpassword" # features/step_definitions/ui_steps.rb:34
    Then I should be on the login page                    # features/step_definitions/ui_steps.rb:42
    And I should see error "Invalid email or password"    # features/step_definitions/ui_steps.rb:48

4 scenarios (4 passed)
22 steps (22 passed)
0m8.086s
Coverage report generated for Cucumber Features to /home/workspace/backoffice/coverage. 463 / 1025 LOC (45.17%) covered.
[CucumberReportPublisher] Compiling Cucumber Html Reports ...
[CucumberReportPublisher] copying all json files from: /home/workspace/backoffice/coverage to reports directory: /var/lib/jenkins/jobs/BackOffice/builds/2014-09-09_12-26-54/cucumber-html-reports
[CucumberReportPublisher] Found the following number of json files: 2
[CucumberReportPublisher] 0. Found a json file: .last_run.json
[CucumberReportPublisher] 1. Found a json file: .resultset.json
[CucumberReportPublisher] Generating HTML reports
Finished: SUCCESS

**Comment by damianszczepanik** [comment]
If you still have this problem, let me know
