### ISSUE TITLE
Seems to be pulling in too much information - Not respecting my decision for relative path

### ISSUE THREAD

**Issue by JasonSmiley** [damianszczepanik/cucumber-reporting-jenkins#109]
So I am generating 3 different reports for this tool

1) the Full run report (1st run of suite) - has its own directory - target/artifacts/target/full-reports/
2) the Rerun report (2nd run of failed tests) - has its own directory - target/artifacts/target/rerun-reports/
3) the latest report (most recent run) - has its own directory - target/artifacts/targat/jenkins-reports/

I want the cucumber report to only look at the results in the 3rd directory, however, it seems to be pulling them all. (I see the test names appearing 3 times in the report)

I am probably doing something wrong but your documentation doesn't specify how to set the directory. Only that it can be set.

I am currently doing this:

target/artifacts/targat/jenkins-reports/

But this is pulling everything instead of only what I asked. Is this a bug or am I doing something wrong?

**Comment by damianszczepanik** [comment]
Recently this part of the plugin was completlly refactored and issue should be gone
