### ISSUE TITLE
404 when accessing cucumber report in jenkins

### ISSUE THREAD

**Issue by shavo007** [damianszczepanik/cucumber-reporting-jenkins#112]
I have many jobs that run cucumber tests on top of selenium.

I configured two jobs for cucumber reports. One job I can access the report, the other I cannot. 

In the failed report, i see in the console the following trace:

[CucumberReportPublisher] Compiling Cucumber Html Reports ...
[CucumberReportPublisher] detected this build is running on the master 
[CucumberReportPublisher] copying json to reports directory: e:\jenkins\jobs\15.1_SELENIUM_CHROME_Payments_Create_Intl\builds\2014-11-28_03-54-46\cucumber-html-reports
[CucumberReportPublisher] Generating HTML reports

The json is quite large. Unfortunately I cannot attach it here.  When I copy the json response into json-lint.com, it complains it is not valid json.

**Comment by tzhotmail** [comment]
Hi,
I am also get 404 error in jenkins 1.610, The version cucumber report plugin I am using is 0.0.24, json file and reports are generated, Is there a sample project that I can use as reference for Cucumber jvm intergration

**Comment by caspermadsen** [comment]
We see the same issue with the 404 after getting a report generated successfully : 

We haven't made any advanced configurations - everything is default.
http://ap-calypbld1p:8080/jenkins/job/build_nightly/cucumber-html-reports/

This is from the build report : 
```
Archiving artifacts
Recording test results
[CucumberReportPublisher] Compiling Cucumber Html Reports ...
[CucumberReportPublisher] Copying all json files from: /build/jobs/build_nightly/workspace/default to reports directory: /build/jobs/build_nightly/configurations/builds/2015-05-18_15-52-20/cucumber-html-reports
[CucumberReportPublisher] Found 1 json files.
[CucumberReportPublisher] 0. Found a json file: CalypsoCustom/build/test-results/cucumber.json
[CucumberReportPublisher] Generating HTML reports
Finished: SUCCESS
```

We are using :
org.jenkins-ci.main:jenkins-war:1.579
net.masterthought.jenkins:cucumber-reports:0.1.0-SNAPSHOT
net.masterthought:cucumber-reporting:0.1.0

BR Casper

**Comment by damianszczepanik** [comment]
``[CucumberReportPublisher] 0. Found a json file: CalypsoCustom/build/test-results/cucumber.json``

means that report which is needed by cucumber-plugin is not found or rather does not exist (if you use default configuration).

That's not a cucumber-plugin problem then but Jenkins issue or cucumber-jwm which did not generate json file

**Comment by damianszczepanik** [comment]
My mistake, json was found but there was some problem with this file. Can you attach it?

**Comment by damianszczepanik** [comment]
To all that still have such problem - test with last release which should log reason of failure (if any) and if it does not work - attach json file
