### ISSUE TITLE
Driver setup failed test cases considered as PASS in final report 0.0.23

### ISSUE THREAD

**Issue by Nishanthshettar** [damianszczepanik/cucumber-reporting-jenkins#114]
Hi, 

Am using latest 0.0.23 plugin in Jenkins job, using BDD framework.

"compile group: 'net.masterthought', name: 'cucumber-reporting', version: '0.0.23'

Whenever driver setup fails bunch of test cases which are tagged in a Test Tag is considered as PASS.

Can someone please look on to this.

Thanks,
Nishanth

**Comment by kingsleyh** [comment]
Hi

Are the tests marked as pass in the cucumber json or just by the plugin? Do you have some example json

**Comment by Nishanthshettar** [comment]
JSON output for this, 

        "description": "",
        "name": "Verify an alert displayed when only optional field is entered",
        "keyword": "Scenario Outline",
        "line": 117,
        "steps": [
          {
            "result": {
              "status": "skipped"
            },
            "name": "Moderator join the meeting using SIPy",
            "keyword": "Given ",
            "line": 108,
            "match": {
              "location": "CommonSteps.Meetme_Moderator_join_the_meeting_using_SIPy()"
            }
          },
          {
            "result": {
              "status": "skipped"
            },
            "name": "Moderator goes air via api",
            "keyword": "Given ",
            "line": 109,
            "match": {
              "location": "CommonSteps.Meetme_go_air()"
            }
          },
          {
            "result": {
              "status": "skipped"
            },
            "name": "From the app I join event as \"presenter\"",
            "keyword": "And ",
            "line": 110,
            "match": {
              "arguments": [
                {
                  "val": "presenter",
                  "offset": 30
                }
              ],
              "location": "EventDetailsSteps.From_app_I_Join__event(String)"
            },
            "matchedColumns": [
              0
            ]
          },
          {
            "result": {
              "status": "skipped"
            },
            "name": "User lands on Event registration page",
            "keyword": "Given ",
            "line": 111,
            "match": {
              "location": "RegistrationSteps.User_lands_on_Event_registration_page()"
            }
          },
          {
            "result": {
              "status": "skipped"
            },
            "name": "User enter the Email id and Lastname",
            "keyword": "When ",
            "line": 112,
            "match": {
              "location": "RegistrationSteps.User_enter_the_Email_id__and_Lastname()"
            }
          },
          {
            "result": {
              "status": "skipped"
            },
            "name": "User is alerted with notification Can\u0027t join event and OK button.",
            "keyword": "Then ",
            "line": 113,
            "match": {
              "location": "RegistrationSteps.User_is_alerted_with_notification_Can_t_join_event_and_OK_button()"
            },
            "output": [
              "\u003c/br\u003eCould not capture browser logs for failed scenario \u003c/br\u003e",
              null
            ]
          }
        ],
        "type": "scenario"
      }
    ],
    "uri": "features/mobile/Registration.feature"
  },
  {
    "id": "search-of-panelist-and-attendee",
    "tags": [
      {
        "name": "@mobile",
        "line": 1
      },
      {
        "name": "@sipp",
        "line": 1
      },
      {
        "name": "@regression",
        "line": 1
      },
      {
        "name": "@search",
        "line": 1
      },
      {
        "name": "@publicEventForMobile",
        "line": 1
      },
      {
        "name": "@deleteEvent",
        "line": 1
      },
      {
        "name": "@terminateMeeting",
        "line": 1
      }
    ],
    "description": "",

Yes, looks like like tests are marked has pass from cucumber plugin.

**Comment by kingsleyh** [comment]
Looks like all the steps are skipped - I think by default it passes on skipped tests - but you can set fail on skipped in the plugin preferences.

—K

**Comment by damianszczepanik** [comment]
Any update about this?
