### ISSUE TITLE
Parameters not working on path

### ISSUE THREAD

**Issue by dariogriffo** [damianszczepanik/cucumber-reporting-jenkins#116]
When using a parameter as part of the path for publishing reports is not translated.
See attached file for example.
I get the %Version% from my git tag
![cucumber_version](https://cloud.githubusercontent.com/assets/3247183/6464072/93580fee-c1af-11e4-87e9-135520ddb211.png)

**Comment by damianszczepanik** [comment]
Can you attach json file?

**Comment by jzang** [comment]
I have similar issue as well. 

[CucumberReportPublisher] copying all json files from slave: \\10.xx.xx.xx\automation\Logs\xx_xx_QAxx\Build_%BUILD_NUMBER% to master reports directory:
