### ISSUE TITLE
Issue Generating reports

### ISSUE THREAD

**Issue by uscengineer** [damianszczepanik/cucumber-reporting-jenkins#117]
Here is the console output:
cucumber features/frontend/mytest.feature --format json --out cucumber.json

[CucumberReportPublisher] Compiling Cucumber Html Reports ...
[CucumberReportPublisher] copying all json files from: /Users/myUser/.jenkins/jobs/QA Automation/workspace to reports directory: /Users/myUser/.jenkins/jobs/QA Automation/builds/43/cucumber-html-reports
[CucumberReportPublisher] there were no json results found in: /Users/myUser/.jenkins/jobs/QA Automation/builds/43/cucumber-html-reports
Finished: SUCCESS

It looks like the cucumber.json file is is copied to /Users/myUser/.jenkins/jobs/QA Automation/builds/43/ not /Users/myUser/.jenkins/jobs/QA Automation/builds/43/cucumber-html-reports as written above. It is probably why there was no json result found.

Json Reports Path: /
Plugin Url Path: blank
jenkins url: http://localhost:8080

Anything I can change to fix this? I am using v0.0.23

Thanks!

**Comment by kingsleyh** [comment]
Hmm not sure - maybe try with 0.0.24 see if it has same issue

**Comment by uscengineer** [comment]
Tried that but it did not work.

**Comment by kingsleyh** [comment]
Is cucumber reports copying the json file into the wrong directory? Seems strange. Are you sure cucumber is outputting the json in the correct place?

**Comment by damianszczepanik** [comment]
I think this is problem with failure of cucumber-jvm or rather invalid plugin configuration. It should not point to this directory. Try with default configuration and should be fine.
