### ISSUE TITLE
Report scenarios/steps rounds down for % success

### ISSUE THREAD

**Issue by dleblanc** [damianszczepanik/cucumber-reporting-jenkins#118]
I would like the reports to never show a success rate of 100% if there's any failures - even if there's only 1 failure in 1 million tests.

Currently it shows a success rate of 100% when there's only a small number of failures.

**Comment by damianszczepanik** [comment]
Sounds like problem with rounding. If you have 3 failures of 1 000 000 steps/features - well that might be 100 or 99 :)

Attach file and describe what exactly you want to see in results so I can understand it better.

**Comment by damianszczepanik** [comment]
The same as damianszczepanik/cucumber-reporting/issues/86
