### ISSUE TITLE
"Publish cucumber results as a report" action is missing

### ISSUE THREAD

**Issue by lookitup4me** [damianszczepanik/cucumber-reporting-jenkins#122]
Hi Kingsley

I installed your awesome plugin cucumber-reports 0.0.24 in Jenkins on my laptop and it works correctly. But when I install the plugin on my Jenkins server, I cannot find the "post build action" called "Publish cucumber results as a report".

So far, I have uninstalled and reinstalled the plugin, restarted jenkins multiple times. I dont think it is my version of jenkins that is to blame but for the record it is Jenkins ver. 1.581.

Do you know if there is something I can do to make the action appear?

Thanks
John

**Comment by devanshu20** [comment]
I am experiencing same issue, Did anyone find any resolution? Plugin works fine on my own machine but won't display "Publish cucumber results as a report" action at my work Jenkins server, By the way I am using Plug in  Version 0.1.0 and Jenkins server version 1.598

**Comment by damianszczepanik** [comment]
You should report this problem to Jenkins team so they can take a look why this plugin is sometimes visible, sometimes not

**Comment by devanshu20** [comment]
Thank you damianszczepanik,

I forgot to mentioned that this was not working because of Jenkins older version, Have installed latest version of Jenkins and Plugin works fine.

Thank you.

**Comment by vveliev** [comment]
if plugin requires newer version of Jenkins then it should say so, before the update .....

**Comment by damianszczepanik** [comment]
Plugin requirements have not changed

**Comment by vveliev** [comment]
So I have Jenkins ver. 1.602 , and after plugin update I do not see "Publish cucumber results as a report"

If solution to the problem: "Update jenkins to the latest version" then it should say that newer version of jenkins is required before update.

**Comment by damianszczepanik** [comment]
I'm using Jenkins ver. 1.626 and there were no problem with plugin upgrade

**Comment by vveliev** [comment]
Often it's expensive to update jenkins and it's good when before update to newer version , plugin tells you that it may not work correctly and jenkins need's to be updated.... 
example: 
![screenshot from 2015-09-02 10 23 48](https://cloud.githubusercontent.com/assets/5420655/9633816/c4b2c4de-515c-11e5-996c-25ec2ef3905f.png)

This is great work done! But it would be nice to know if plugin may not work after update.
