### ISSUE TITLE
Error with "java.lang.NoClassDefFoundError:"

### ISSUE THREAD

**Issue by XGWang0** [damianszczepanik/cucumber-reporting-jenkins#126]
I have a json file in my slave, my slave java version : java version "1.7.0"
my jenkins server java version is ： java version "1.6.0"

json file :
===================
[
    {
        "description": "aaaaaaaaaaa", 
        "elements": [
            {
                "keyword": "Scenario",  
                "name": "SLES-11-SP4-64.KVM", 
                "steps": [
                    {
                        "keyword": "Install host",
                        "name": "Install host",
                        "result": {
                            "duration": 8007,
                            "status": "passed"
                        }
                    }, 
                    {
                        "keyword": "Install guest", 
                        "name": "Install guest", 
                        "result": {
                            "duration": 8576, 
                            "status": "passed"
                        }
                    }
                ], 
                "type": "scenario"
            }, 
            {
                "keyword": "Scenario", 
                "name": "SLES-12-FCS-64.KVM", 
                "steps": [
                    {
                        "keyword": "Install host", 
                        "name": "Install host", 
                        "result": {
                            "duration": 7943, 
                            "status": "passed"
                        }
                    }, 
                    {
                        "keyword": "Install guest", 
                        "name": "Install guest", 
                        "result": {
                            "duration": 7967, 
                            "status": "passed"
                        }
                    }
                ], 
                "type": "scenario"
            }, 
            {
                "keyword": "Scenario", 
                "name": "SLES-12-FCS-64.KVM", 
                "steps": [
                    {
                        "keyword": "Install host", 
                        "name": "Install host", 
                        "result": {
                            "duration": 7943, 
                            "status": "passed"
                        }
                    }, 
                    {
                        "keyword": "Install guest", 
                        "name": "Install guest", 
                        "result": {
                            "duration": 7967, 
                            "status": "passed"
                        }
                    }
                ], 
                "type": "scenario"
            }
        ],
        "keyword": "Feature",
        "name": "147.2.207.27",
        "uri": "147.2.207.27"
    }
]
==================================

After run a job on jenkins,  the job console shows the cucmber report failure.

ERROR: Publisher net.masterthought.jenkins.CucumberReportPublisher aborted due to exception
java.lang.NoClassDefFoundError: net/masterthought/cucumber/ReportBuilder
	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:109)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:761)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:721)
	at hudson.model.Build$BuildExecution.post2(Build.java:183)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:670)
	at hudson.model.Run.execute(Run.java:1776)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:89)
	at hudson.model.Executor.run(Executor.java:240)

**Comment by damianszczepanik** [comment]
Rather problem with Jenkins/agent than plugin itself
