### ISSUE TITLE
Not All Test Steps are displayed

### ISSUE THREAD

**Issue by jeremyjjbrown** [damianszczepanik/cucumber-reporting-jenkins#129]
All of my test steps are not displayed in the fancy Cucumber Reports page.

### Test output
![screenshot 2015-05-29 07 52 08](https://cloud.githubusercontent.com/assets/1660010/7883009/b5b08f0e-05d8-11e5-8823-a27cd32699a7.png)

### Screen Display
![screen shot 2015-05-29 at 08 00 25](https://cloud.githubusercontent.com/assets/1660010/7883021/dd5a6106-05d8-11e5-9887-297065af0375.png)

### cucumber.json
[
  {
    "comments": [
      {
        "line": 1,
        "value": "#"
      },
      {
        "line": 2,
        "value": "# language: en"
      },
      {
        "line": 3,
        "value": "#"
      }
    ],
    "line": 4,
    "elements": [
      {
        "line": 7,
        "name": "",
        "description": "",
        "type": "background",
        "keyword": "Background",
        "steps": [
          {
            "output": [
              "\n  Kannon deployment image: docker.sdp.in.here.com/here/java-webapp-deploy"
            ],
            "result": {
              "duration": 202840007,
              "status": "passed"
            },
            "line": 8,
            "name": "a Kannon deployment image from the environmental variable KANNON_DEPLOY_IMAGE",
            "match": {
              "arguments": [
                {
                  "val": "KANNON_DEPLOY_IMAGE",
                  "offset": 58
                }
              ],
              "location": "KannonTestSteps.groovy:49"
            },
            "keyword": "Given "
          }
        ]
      },
      {
        "before": [
          {
            "result": {
              "duration": 229825,
              "status": "passed"
            },
            "match": {
              "location": "KannonTestSteps.groovy:27"
            }
          },
          {
            "result": {
              "duration": 41719,
              "status": "passed"
            },
            "match": {
              "location": "WebserviceTestSteps.groovy:16"
            }
          },
          {
            "result": {
              "duration": 57908,
              "status": "passed"
            },
            "match": {
              "location": "KannonTestSteps.groovy:27"
            }
          },
          {
            "result": {
              "duration": 102993,
              "status": "passed"
            },
            "match": {
              "location": "WebserviceTestSteps.groovy:16"
            }
          }
        ],
        "line": 10,
        "name": "The application is deployed",
        "description": "",
        "id": "kannon-docker-container-orchestration.;the-application-is-deployed",
        "type": "scenario",
        "keyword": "Scenario",
        "steps": [
          {
            "result": {
              "duration": 1307932477146,
              "status": "passed"
            },
            "line": 11,
            "name": "calling the Kannon action --base-namespace\u003dpat-test deploy dev",
            "match": {
              "arguments": [
                {
                  "val": "--base-namespace\u003dpat-test deploy dev",
                  "offset": 26
                }
              ],
              "location": "KannonTestSteps.groovy:59"
            },
            "keyword": "When "
          },
          {
            "output": [
              "    a Cloudformation Stack named pat-test-example-java-webapp should be deployed"
            ],
            "result": {
              "duration": 2160990837,
              "status": "passed"
            },
            "line": 12,
            "name": "a Cloudformation Stack named pat-test-example-java-webapp should be deployed",
            "match": {
              "arguments": [
                {
                  "val": "pat-test-example-java-webapp",
                  "offset": 29
                }
              ],
              "location": "KannonTestSteps.groovy:96"
            },
            "keyword": "Then "
          },
          {
            "output": [
              "    a Cloudformation Stack named pat-test-example-frontend should be deployed"
            ],
            "result": {
              "duration": 315101812,
              "status": "passed"
            },
            "line": 13,
            "name": "a Cloudformation Stack named pat-test-example-frontend should be deployed",
            "match": {
              "arguments": [
                {
                  "val": "pat-test-example-frontend",
                  "offset": 29
                }
              ],
              "location": "KannonTestSteps.groovy:96"
            },
            "keyword": "And "
          },
          {
            "output": [
              "    a ELB with DNS internal-pat-test-example-frontend-ELB-208888930.us-east-1.elb.amazonaws.com should be running"
            ],
            "result": {
              "duration": 221132441,
              "status": "passed"
            },
            "line": 14,
            "name": "an ELB for a Cloudformation Stack named pat-test-example-frontend should be deployed",
            "match": {
              "arguments": [
                {
                  "val": "pat-test-example-frontend",
                  "offset": 40
                }
              ],
              "location": "KannonTestSteps.groovy:111"
            },
            "keyword": "And "
          }
        ]
      },
      {
        "line": 7,
        "name": "",
        "description": "",
        "type": "background",
        "keyword": "Background",
        "steps": [
          {
            "output": [
              "\n  Kannon deployment image: docker.sdp.in.here.com/here/java-webapp-deploy"
            ],
            "result": {
              "duration": 2263279,
              "status": "passed"
            },
            "line": 8,
            "name": "a Kannon deployment image from the environmental variable KANNON_DEPLOY_IMAGE",
            "match": {
              "arguments": [
                {
                  "val": "KANNON_DEPLOY_IMAGE",
                  "offset": 58
                }
              ],
              "location": "KannonTestSteps.groovy:49"
            },
            "keyword": "Given "
          }
        ]
      },
      {
        "before": [
          {
            "result": {
              "duration": 28797,
              "status": "passed"
            },
            "match": {
              "location": "KannonTestSteps.groovy:27"
            }
          },
          {
            "result": {
              "duration": 22900,
              "status": "passed"
            },
            "match": {
              "location": "WebserviceTestSteps.groovy:16"
            }
          }
        ],
        "line": 16,
        "name": "SDP Frontend is up",
        "description": "",
        "id": "kannon-docker-container-orchestration.;sdp-frontend-is-up",
        "type": "scenario",
        "keyword": "Scenario",
        "steps": [
          {
            "output": [
              "    calling a get request to: http://internal-pat-test-example-frontend-ELB-208888930.us-east-1.elb.amazonaws.com"
            ],
            "result": {
              "duration": 60134501992,
              "status": "passed"
            },
            "line": 17,
            "name": "calling a get request to /health",
            "match": {
              "arguments": [
                {
                  "val": "/health",
                  "offset": 25
                }
              ],
              "location": "KannonTestSteps.groovy:173"
            },
            "keyword": "When "
          },
          {
            "result": {
              "duration": 840573,
              "status": "passed"
            },
            "line": 18,
            "name": "the status code returned should be 200",
            "match": {
              "arguments": [
                {
                  "val": "200",
                  "offset": 35
                }
              ],
              "location": "KannonTestSteps.groovy:193"
            },
            "keyword": "Then "
          },
          {
            "result": {
              "duration": 4473922,
              "status": "passed"
            },
            "line": 19,
            "name": "the json response returned should contain OK",
            "match": {
              "arguments": [
                {
                  "val": "OK",
                  "offset": 42
                }
              ],
              "location": "KannonTestSteps.groovy:200"
            },
            "keyword": "And "
          }
        ]
      },
      {
        "line": 7,
        "name": "",
        "description": "",
        "type": "background",
        "keyword": "Background",
        "steps": [
          {
            "output": [
              "\n  Kannon deployment image: docker.sdp.in.here.com/here/java-webapp-deploy"
            ],
            "result": {
              "duration": 184562,
              "status": "passed"
            },
            "line": 8,
            "name": "a Kannon deployment image from the environmental variable KANNON_DEPLOY_IMAGE",
            "match": {
              "arguments": [
                {
                  "val": "KANNON_DEPLOY_IMAGE",
                  "offset": 58
                }
              ],
              "location": "KannonTestSteps.groovy:49"
            },
            "keyword": "Given "
          }
        ]
      },
      {
        "before": [
          {
            "result": {
              "duration": 25656,
              "status": "passed"
            },
            "match": {
              "location": "KannonTestSteps.groovy:27"
            }
          },
          {
            "result": {
              "duration": 29028,
              "status": "passed"
            },
            "match": {
              "location": "WebserviceTestSteps.groovy:16"
            }
          }
        ],
        "line": 21,
        "name": "Sentry is working on the SDP Frontend",
        "description": "",
        "id": "kannon-docker-container-orchestration.;sentry-is-working-on-the-sdp-frontend",
        "type": "scenario",
        "keyword": "Scenario",
        "steps": [
          {
            "output": [
              "    calling a get request to: http://internal-pat-test-example-frontend-ELB-208888930.us-east-1.elb.amazonaws.com"
            ],
            "result": {
              "duration": 60035882648,
              "status": "passed"
            },
            "line": 22,
            "name": "calling a get request to /sentry-status",
            "match": {
              "arguments": [
                {
                  "val": "/sentry-status",
                  "offset": 25
                }
              ],
              "location": "KannonTestSteps.groovy:173"
            },
            "keyword": "When "
          },
          {
            "result": {
              "duration": 119253,
              "status": "passed"
            },
            "line": 23,
            "name": "the status code returned should be 200",
            "match": {
              "arguments": [
                {
                  "val": "200",
                  "offset": 35
                }
              ],
              "location": "KannonTestSteps.groovy:193"
            },
            "keyword": "Then "
          },
          {
            "result": {
              "duration": 109261,
              "status": "passed"
            },
            "line": 24,
            "name": "the json response returned should contain \"sentry\":\"on\"",
            "match": {
              "arguments": [
                {
                  "val": "\"sentry\":\"on\"",
                  "offset": 42
                }
              ],
              "location": "KannonTestSteps.groovy:200"
            },
            "keyword": "And "
          }
        ]
      },
      {
        "line": 7,
        "name": "",
        "description": "",
        "type": "background",
        "keyword": "Background",
        "steps": [
          {
            "output": [
              "\n  Kannon deployment image: docker.sdp.in.here.com/here/java-webapp-deploy"
            ],
            "result": {
              "duration": 223921,
              "status": "passed"
            },
            "line": 8,
            "name": "a Kannon deployment image from the environmental variable KANNON_DEPLOY_IMAGE",
            "match": {
              "arguments": [
                {
                  "val": "KANNON_DEPLOY_IMAGE",
                  "offset": 58
                }
              ],
              "location": "KannonTestSteps.groovy:49"
            },
            "keyword": "Given "
          }
        ]
      },
      {
        "before": [
          {
            "result": {
              "duration": 32575,
              "status": "passed"
            },
            "match": {
              "location": "KannonTestSteps.groovy:27"
            }
          },
          {
            "result": {
              "duration": 35126,
              "status": "passed"
            },
            "match": {
              "location": "WebserviceTestSteps.groovy:16"
            }
          }
        ],
        "line": 26,
        "name": "Sentry is protecting the backend",
        "description": "",
        "id": "kannon-docker-container-orchestration.;sentry-is-protecting-the-backend",
        "type": "scenario",
        "keyword": "Scenario",
        "steps": [
          {
            "output": [
              "    calling a get request to: http://internal-pat-test-example-frontend-ELB-208888930.us-east-1.elb.amazonaws.com"
            ],
            "result": {
              "duration": 180144043163,
              "status": "passed"
            },
            "line": 27,
            "name": "calling a get request to /",
            "match": {
              "arguments": [
                {
                  "val": "/",
                  "offset": 25
                }
              ],
              "location": "KannonTestSteps.groovy:173"
            },
            "keyword": "When "
          },
          {
            "result": {
              "duration": 113636,
              "status": "passed"
            },
            "line": 28,
            "name": "the status code returned should be 400",
            "match": {
              "arguments": [
                {
                  "val": "400",
                  "offset": 35
                }
              ],
              "location": "KannonTestSteps.groovy:193"
            },
            "keyword": "Then "
          }
        ]
      },
      {
        "line": 7,
        "name": "",
        "description": "",
        "type": "background",
        "keyword": "Background",
        "steps": [
          {
            "output": [
              "\n  Kannon deployment image: docker.sdp.in.here.com/here/java-webapp-deploy"
            ],
            "result": {
              "duration": 237025,
              "status": "passed"
            },
            "line": 8,
            "name": "a Kannon deployment image from the environmental variable KANNON_DEPLOY_IMAGE",
            "match": {
              "arguments": [
                {
                  "val": "KANNON_DEPLOY_IMAGE",
                  "offset": 58
                }
              ],
              "location": "KannonTestSteps.groovy:49"
            },
            "keyword": "Given "
          }
        ]
      },
      {
        "before": [
          {
            "result": {
              "duration": 25247,
              "status": "passed"
            },
            "match": {
              "location": "KannonTestSteps.groovy:27"
            }
          },
          {
            "result": {
              "duration": 21073,
              "status": "passed"
            },
            "match": {
              "location": "WebserviceTestSteps.groovy:16"
            }
          }
        ],
        "line": 30,
        "name": "Tomcat is working on the SDP Backend",
        "description": "",
        "id": "kannon-docker-container-orchestration.;tomcat-is-working-on-the-sdp-backend",
        "type": "scenario",
        "keyword": "Scenario",
        "steps": [
          {
            "output": [
              "    calling a get request to: http://internal-pat-test-example-frontend-ELB-208888930.us-east-1.elb.amazonaws.com"
            ],
            "result": {
              "duration": 60048677490,
              "status": "passed"
            },
            "line": 31,
            "name": "calling a get request to /?app_id\u003dBGhEF8nmnsuva0r94wMo\u0026app_code\u****************,
            "match": {
              "arguments": [
                {
                  "val": "/?app_id\u003dBGhEF8nmnsuva0r94wMo\u0026app_code\u************************",
                  "offset": 25
                }
              ],
              "location": "KannonTestSteps.groovy:173"
            },
            "keyword": "When "
          },
          {
            "result": {
              "duration": 125222,
              "status": "passed"
            },
            "line": 32,
            "name": "the status code returned should be 200",
            "match": {
              "arguments": [
                {
                  "val": "200",
                  "offset": 35
                }
              ],
              "location": "KannonTestSteps.groovy:193"
            },
            "keyword": "Then "
          },
          {
            "result": {
              "duration": 81957,
              "status": "passed"
            },
            "line": 33,
            "name": "the json response returned should contain \u003ctitle\u003eApache Tomcat",
            "match": {
              "arguments": [
                {
                  "val": "\u003ctitle\u003eApache Tomcat",
                  "offset": 42
                }
              ],
              "location": "KannonTestSteps.groovy:200"
            },
            "keyword": "And "
          }
        ]
      },
      {
        "line": 7,
        "name": "",
        "description": "",
        "type": "background",
        "keyword": "Background",
        "steps": [
          {
            "output": [
              "\n  Kannon deployment image: docker.sdp.in.here.com/here/java-webapp-deploy"
            ],
            "result": {
              "duration": 163137,
              "status": "passed"
            },
            "line": 8,
            "name": "a Kannon deployment image from the environmental variable KANNON_DEPLOY_IMAGE",
            "match": {
              "arguments": [
                {
                  "val": "KANNON_DEPLOY_IMAGE",
                  "offset": 58
                }
              ],
              "location": "KannonTestSteps.groovy:49"
            },
            "keyword": "Given "
          }
        ]
      },
      {
        "before": [
          {
            "result": {
              "duration": 270245,
              "status": "passed"
            },
            "match": {
              "location": "KannonTestSteps.groovy:27"
            }
          },
          {
            "result": {
              "duration": 38579,
              "status": "passed"
            },
            "match": {
              "location": "WebserviceTestSteps.groovy:16"
            }
          }
        ],
        "line": 35,
        "name": "Consul Health Checks are registered",
        "description": "",
        "id": "kannon-docker-container-orchestration.;consul-health-checks-are-registered",
        "type": "scenario",
        "keyword": "Scenario",
        "steps": [
          {
            "output": [
              "    calling the Consul DC url: consul.sdp-dev-aws-us-east-1.sdp.in.here.com:8500"
            ],
            "result": {
              "duration": 216843,
              "status": "passed"
            },
            "line": 36,
            "name": "calling the Consul DC url consul.sdp-dev-aws-us-east-1.sdp.in.here.com:8500",
            "match": {
              "arguments": [
                {
                  "val": "consul.sdp-dev-aws-us-east-1.sdp.in.here.com:8500",
                  "offset": 26
                }
              ],
              "location": "KannonTestSteps.groovy:151"
            },
            "keyword": "When "
          },
          {
            "output": [
              "    a Consul Health Check named test-dev-frontend-nginx should be registered in dc sdp-dev-aws-us-east-1"
            ],
            "result": {
              "duration": 156884464,
              "status": "passed"
            },
            "line": 37,
            "name": "a Consul Health Check named test-dev-frontend-nginx should be registered in dc sdp-dev-aws-us-east-1",
            "match": {
              "arguments": [
                {
                  "val": "test-dev-frontend-nginx",
                  "offset": 28
                },
                {
                  "val": "sdp-dev-aws-us-east-1",
                  "offset": 79
                }
              ],
              "location": "KannonTestSteps.groovy:160"
            },
            "keyword": "Then "
          },
          {
            "output": [
              "    a Consul Health Check named test-dev-java-webapp-tomcat should be registered in dc sdp-dev-aws-us-east-1"
            ],
            "result": {
              "duration": 7972996,
              "status": "passed"
            },
            "line": 38,
            "name": "a Consul Health Check named test-dev-java-webapp-tomcat should be registered in dc sdp-dev-aws-us-east-1",
            "match": {
              "arguments": [
                {
                  "val": "test-dev-java-webapp-tomcat",
                  "offset": 28
                },
                {
                  "val": "sdp-dev-aws-us-east-1",
                  "offset": 83
                }
              ],
              "location": "KannonTestSteps.groovy:160"
            },
            "keyword": "Then "
          }
        ]
      },
      {
        "line": 7,
        "name": "",
        "description": "",
        "type": "background",
        "keyword": "Background",
        "steps": [
          {
            "output": [
              "\n  Kannon deployment image: docker.sdp.in.here.com/here/java-webapp-deploy"
            ],
            "result": {
              "duration": 3497377,
              "status": "passed"
            },
            "line": 8,
            "name": "a Kannon deployment image from the environmental variable KANNON_DEPLOY_IMAGE",
            "match": {
              "arguments": [
                {
                  "val": "KANNON_DEPLOY_IMAGE",
                  "offset": 58
                }
              ],
              "location": "KannonTestSteps.groovy:49"
            },
            "keyword": "Given "
          }
        ]
      },
      {
        "line": 40,
        "name": "The application is undeployed",
        "description": "",
        "id": "kannon-docker-container-orchestration.;the-application-is-undeployed",
        "type": "scenario",
        "keyword": "Scenario",
        "steps": [
          {
            "result": {
              "duration": 405140240210,
              "status": "passed"
            },
            "line": 41,
            "name": "calling the Kannon action --base-namespace\u003dpat-test undeploy dev",
            "match": {
              "arguments": [
                {
                  "val": "--base-namespace\u003dpat-test undeploy dev",
                  "offset": 26
                }
              ],
              "location": "KannonTestSteps.groovy:59"
            },
            "keyword": "When "
          },
          {
            "output": [
              "    the Cloudformation Stack named pat-test-example-java-webapp should be deleted"
            ],
            "result": {
              "duration": 300453074,
              "status": "passed"
            },
            "line": 42,
            "name": "a Cloudformation Stack named pat-test-example-java-webapp should not be deployed",
            "match": {
              "arguments": [
                {
                  "val": "pat-test-example-java-webapp",
                  "offset": 29
                }
              ],
              "location": "KannonTestSteps.groovy:128"
            },
            "keyword": "Then "
          },
          {
            "output": [
              "    the Cloudformation Stack named pat-test-example-frontend should be deleted"
            ],
            "result": {
              "duration": 243641850,
              "status": "passed"
            },
            "line": 43,
            "name": "a Cloudformation Stack named pat-test-example-frontend should not be deployed",
            "match": {
              "arguments": [
                {
                  "val": "pat-test-example-frontend",
                  "offset": 29
                }
              ],
              "location": "KannonTestSteps.groovy:128"
            },
            "keyword": "And "
          }
        ]
      }
    ],
    "name": "Kannon Docker Container Orchestration.",
    "description": " Deploy a Service, Frontend Tier, and Sentry using Kannon.",
    "id": "kannon-docker-container-orchestration.",
    "keyword": "Feature",
    "uri": "11-kannon-docker-host-actions.feature"
  }
]

**Comment by BogdanLivadariu** [comment]
it looks like you only have a single feature here, you might have issues with the fact that the cucumber.json file is overridden by the last test that is run.

Try to force the tests to log into different json files, maybe this sorts out your problem

**Comment by damianszczepanik** [comment]
https://jsonformatter.curiousconcept.com/ says this json file is not valid - please attach file instead copying it since it includes some unusual characters
