### ISSUE TITLE
[Enhancement] how can i add a external link for a scenario section?

### ISSUE THREAD

**Issue by XGWang0** [damianszczepanik/cucumber-reporting-jenkins#130]
hi kingsleyh :
Usually, we may meet some requirement about a external link, it is that i want to add a web link address to scenario section (may be adding the external link to end of scenario name or other place) in json file, but  i try to add this content "\<a href=www.google.com\>detai\</a\> " to scenario name, the string will be display crudely instead of a link to www.google.com website.

In addition, i try to add statement " "description": "scenario description" " to scenario section in json file , the report can not display the description content.

My cucumber plug-in version is 0.1.0,   
kingsleyh , can you help me to solve external link issue ?  even a workaround.

**Comment by damianszczepanik** [comment]
You can write some logs
http://cucumber.github.io/api/cucumber/jvm/javadoc/cucumber/api/Scenario.html#write-java.lang.String-
