### ISSUE TITLE
Add support for embedded media

### ISSUE THREAD

**Issue by noymn** [damianszczepanik/cucumber-reporting-jenkins#135]
Cucumber allows to embed media into the scenario output (such as images). We should be able to also represent that into the reports.

**Comment by Simon-Kaz** [comment]
works for me, for webdriver tests i have the following:

if(scenario.isFailed()) {
            byte[] screenshot = driver.getScreenshotAs(OutputType.BYTES);
            scenario.embed(screenshot, "image/png");
        }

**Comment by damianszczepanik** [comment]
Images are already supported. Update to the newest version if you have old one already.

**Comment by noymn** [comment]
I currently have a hook that takes screenshots on failure and specific calls to retrieve expected screenshots. I attach them to the scenario through the embed call but afterwards, on generation, the nice report does not show them.
