### ISSUE TITLE
Export to HTML or PDF files

### ISSUE THREAD

**Issue by stephanrauh** [damianszczepanik/cucumber-reporting-jenkins#138]
Is it possible to export the Cucumber test report to a PDF file, or to a folder containing the HTML files needed to display the report? Something that can be viewed without Jenkins?

**Comment by damianszczepanik** [comment]
You can save html locally by coping whole directory or print to PDF. Exporting is not the feature of this plugin and won't be added.

**Comment by stephanrauh** [comment]
Actually, copying the directory was my first idea, but I didn't find it. I had the impression that some of the HTML code is generated on-the-fly. Fancy to tell me which directory you refer to?

**Comment by damianszczepanik** [comment]
Copy
``job/<project>/cucumber-html-reports``

and you will have full report

**Comment by stephanrauh** [comment]
Thanks! Hope I now succeed (but not before Monday :)).
