### ISSUE TITLE
Backgrounds are calculated as Scenario

### ISSUE THREAD

**Issue by xmav000** [damianszczepanik/cucumber-reporting-jenkins#142]
![2015-10-02-cucumberjenkinsreport](https://cloud.githubusercontent.com/assets/14940810/10246982/eee876c4-6915-11e5-81b1-15eac92b2ca5.png)

The background that runs before each Scenario is calculated as Scenario each time it runs.
I have 1 background (Grundlage) for 2 Scenarios (Szenarios) and the result shows 4 Scenarioes as you can see in the attached screenshot.

**Comment by damianszczepanik** [comment]
Can you attach json file?

**Comment by xmav000** [comment]
http://pastebin.com/UJrKASPH  is this ok?

**Comment by damianszczepanik** [comment]
Yes, I will check this soon

**Comment by damianszczepanik** [comment]
Will be fixed with next release
