### ISSUE TITLE
All steps displayed as skipped, wrong number of steps and status of all skipped tests is 'passed'

### ISSUE THREAD

**Issue by trackander** [damianszczepanik/cucumber-reporting-jenkins#144]
Hello. Each of my builds has about 750 passing tests but each is marked as 'skipped' every single time. Additionally, it says there are over 2,000 steps total. Each skipped test is marked as 'passed'.

I have updated to the latest version. Perhaps my config is wrong? It's a freeform jenkins project and am running the plugin inside the calabash folder:

cd /Users/my-company/jenkins/workspace/my-repo-name/mobile
calabash-android run /Users/me/jenkins/workspace/path-to-apk -p android 
features/something.feature
cucumber --format json -o cucumber.json

**Comment by damianszczepanik** [comment]
Attach json file so I can take a look.

**Comment by damianszczepanik** [comment]
No feedback, closing the issue.

**Comment by trackander** [comment]
I apologize for not responding. My wife had some health issues and I was
out of office.I will try to do more troubleshooting when I get back into
this.

Thanks for the response.

On Fri, Nov 13, 2015 at 2:25 PM, Damian Szczepanik <notifications@github.com
