### ISSUE TITLE
Step Statistics "Duration (ms)": 1 million times too large.

### ISSUE THREAD

**Issue by msymons** [damianszczepanik/cucumber-reporting-jenkins#145]
Using cucumber-reporting-jenkins v0.4.0, the "Duration (ms)" column in the "Step Statistics" report is displaying values that are too large, by a factor of a million.

For example, for "Duration" of 59s 999ms, the "Duration (ms)" column is displaying 59999739940.
Should be 599997
See screenshot.

Separately, seeing as how the two Duration columns actually contain the exact same data (just formatted differently), would it not be more useful to divide by the Implemention "Total" and change "Duration (ms)" into "Average Duration (ms)"?    The table already allows dynamic resorting of columns and thus it would be really easy to see which are your genuinely slowest steps.

![steps_duration_values](https://cloud.githubusercontent.com/assets/4938718/11020956/3e7d8afa-8629-11e5-8a1b-f600646896f3.png)

**Comment by damianszczepanik** [comment]
First issue is related to the library I use to format seconds into other values (hours, minutes etc) and looks like its implementation lost precision.

Adding information about average seems to be interesting
