### ISSUE TITLE
Step Statistics Discrepancy With Feature Statistics

### ISSUE THREAD

**Issue by msymons** [damianszczepanik/cucumber-reporting-jenkins#146]
Using cucumber-reporting-jenkins v0.4.0, the Feature Statistics report provides grand totals for number of steps and also for duration.   So does the new Steps Statistics report.

However, the totals are not the same.  Are they not supposed to be the same?

![feature-step-discrepancy](https://cloud.githubusercontent.com/assets/4938718/11021038/bf72e148-862c-11e5-949b-5ca091eb64e4.png)

Aside: great work on the plugin in the last few months!  Thanks for all your efforts.

**Comment by damianszczepanik** [comment]
The reason why those two may not be the same is described at the top of the ;Step' page. If you have background steps the total values may not be the same.

**Comment by msymons** [comment]
My bad... I had seen the warning at the top but then overlooked it later.   However, I am not sure that I understand why background steps would make a difference.  They still get executed as a normal scenario step.

**Comment by damianszczepanik** [comment]
That's some how legacy which I did not change (to keep backwards compatibility).
