### ISSUE TITLE
Screenshot links not being displayed

### ISSUE THREAD

**Issue by mjlepouttre** [damianszczepanik/cucumber-reporting-jenkins#149]
I'm saving screenshots to the report but no link is being displayed to actually view the screenshots.  I've inspected the JSON file itself and the data for the image is there.

**Comment by damianszczepanik** [comment]
Show me json file

**Comment by mjlepouttre** [comment]
"after": [
          {
            "match": {
              "location": "features/support/hooks.rb:22"
            },
            "result": {
              "status": "passed",
              "duration": 2340655241
            }
          },
          {
            "match": {
              "location": "capybara-2.5.0/lib/capybara/cucumber.rb:7"
            },
            "result": {
              "status": "passed",
              "duration": 24704
            },
            "embeddings": [
              {
                "mime_type": "image/png",
                "data": "ZGF0YTppbWFnZS9wbmc7YmFzZTY0LGlWQk9SdzBLR2dvQUFBQU5TVWhFVWdBQUJBNEFBQUtWQ0FJQUFBREF6VDZ0QUFBZ0FFbEVRVlI0bk96ZGVXQVU5Y0gvOGU4ZXMwZXl1VWtJQ1FtNU9NSWRnWEF...

Let me know if you need to see more of the file.

**Comment by damianszczepanik** [comment]
Attach file, not part of the file

**Comment by mjlepouttre** [comment]
[cucumber_json.txt](https://github.com/damianszczepanik/cucumber-reporting-jenkins/files/41673/cucumber_json.txt)

**Comment by damianszczepanik** [comment]
The reason is that {{embedded}} items is currently supported only for {{steps}} while it should be also for {{after}} and {{before}} as descirbed in https://cucumber.io/docs/reference#report-attachments

**Comment by doronzRumble** [comment]
any chance to merge this to cucumber-reporting repo or create a pull request for cucumber-reports-plugin

**Comment by damianszczepanik** [comment]
Will be available in next release.
