### ISSUE TITLE
 Failed steps are not failing the scenario

### ISSUE THREAD

**Issue by clarissaar** [damianszczepanik/cucumber-reporting-jenkins#150]
I'm seeing that background steps are failing, but it's not failing the scenario. Is it an issue?
![Uploading Untitled.png…]()

**Comment by damianszczepanik** [comment]
Backgrounds were removed in damianszczepanik/cucumber-reporting/pull/251 so this problem won't remain. I've checked failed background causes scenario failure.

Wait for next release
