### ISSUE TITLE
browsers prevent any css loading due to CSP violations in the report

### ISSUE THREAD

**Issue by royv-perion** [damianszczepanik/cucumber-reporting-jenkins#152]
cucumber report is showing only text without any CSS styling to due CSP (content security policy) violation:
example from chrome console: 
Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'".

this happens on all major browsers (firefox, ie, chrome).
its possible to turn CSP feature on firefox off and see the report as local workaround.

Jenkins: 1.642
cucumber-reports: 1.0.0
cucumber-plugin: 0.0.2

thanks

**Comment by damianszczepanik** [comment]
Does not happen to me IE/Chrome/Firefox so you can change your permission/configuration to make it work.

Since this is not common issue and I cannot reproduce it I won't take over of this problem soon.

**Comment by damianszczepanik** [comment]
Also please don't report issues to obsolete project as reported in README: https://github.com/damianszczepanik/cucumber-reporting-jenkins
