### ISSUE TITLE
cucumber.json file not being added temp directory created on Jenkins run

### ISSUE THREAD

**Issue by fbravo14** [damianszczepanik/cucumber-reporting-jenkins#154]
A. no cucumber.json file is being created though I have commands in cucumber.yml file
B. I've tried adding mkdir reports && touch /reports/cucumber.json which creates the directory and the file, however json file doesn't get populated, so when I click the Cucumber Reports icon I see the charts, but with zero stats

How or why do these temp files get created in my workspace (e.g. ./reports/2015_12_22_09_45)?

I'm at the mercy of anyone to help me get my cucumber.json to be added to this path on each Jenkins run. I've tried using Json reports path and File Include Path to no avail.

**Comment by damianszczepanik** [comment]
Attach json and logs

**Comment by damianszczepanik** [comment]
If you have problem with creating cucumber.json it means this is not problem with the plugin but cucumber-jvm.
