### ISSUE TITLE
cannot display the cucumber reports

### ISSUE THREAD

**Issue by rlagoue** [damianszczepanik/cucumber-reporting-jenkins#162]
Hello, 

after upgrading to version 2.6.2  the link to the cucumber reports html file no more works. It redirects me to build page. I tried 2.6.3 without success. Now I am look how to downgrade to 2.5.1

cheers

**Comment by damianszczepanik** [comment]
With the last release security was upgraded and it was impossible to keep backwards compatibility. The location to the report has changed, the way how static content is served has changed so new reports will have proper link to new reports but old are not displayed any more.

Sorry for the problem but this changed was requried :(

**Comment by rlagoue** [comment]
ok alright. Thank you for your response
