### ISSUE TITLE
Cucumber Jvm reports are giving java null exception in jenkins

### ISSUE THREAD

**Issue by sreedharkommi** [damianszczepanik/cucumber-reporting-jenkins#164]
Hi,

When i build my cucumber scripts in Jenkins scripts are passing and build is failing due to Cucumber jvm not able to generate the report and marking it as failure. 

Below is the error:
[CucumberReportPublisher] Found the following number of json files: 2
[CucumberReportPublisher] 0. Found a json file: cucumber.json
[CucumberReportPublisher] 1. Found a json file: features/.cucumber/stepdefs.json
[CucumberReportPublisher] Generating HTML reports
[CucumberReportPublisher] there was an error generating the reports: java.lang.NullPointerException
net.masterthought.cucumber.ReportBuilder.getBuildStatus(ReportBuilder.java:76)
net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:112)
hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:770)
hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:734)
hudson.model.Build$BuildExecution.post2(Build.java:183)
hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:683)
hudson.model.Run.execute(Run.java:1784)
hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
hudson.model.ResourceController.execute(ResourceController.java:89)
hudson.model.Executor.run(Executor.java:240)
Build step 'Publish cucumber results as a report' changed build result to FAILURE
Finished: FAILURE

FYI:
We are using Cucumber Jvm reports plugin version is 0.0.23 and Cucumber json test reporting plugin version is 0.8.2.

When i open the cucumber report it is giving error **java.lang.NullPointerException**

Note: When i click on Cucumber JVM report plugin in manage Jenkins it is giving below error.

**Not Found
The requested URL /plugin/cucumber-reports/ was not found on this server.**

**Comment by sreedharkommi** [comment]
Please do needful ASAP.

**Comment by damianszczepanik** [comment]
Attach json file

**Comment by sreedharkommi** [comment]
Please find the json files.

[cucumber.txt](https://github.com/damianszczepanik/cucumber-reporting-jenkins/files/701280/cucumber.txt)
[stepdefs.txt](https://github.com/damianszczepanik/cucumber-reporting-jenkins/files/701281/stepdefs.txt)

**Comment by damianszczepanik** [comment]
Did not notice, you have installed very old version, upgrade plugin then it will work

**Comment by sreedharkommi** [comment]
Hi,

I have upgraded it to latest version(**Cucumber-JVm Reports version - 2.5.1**) still it is giving issues.

**[CucumberReportPublisher] Found 2 json files.
[CucumberReportPublisher] 1. Found a json file: cucumber.json
[CucumberReportPublisher] 2. Found a json file: features/.cucumber/stepdefs.json
[CucumberReportPublisher] Generating HTML reports
Build step 'Cucumber-JVM reports' changed build result to FAILURE
Finished: FAILURE**


And when i click on cucumber-jvm report it is giving below error.

**Error
Something went wrong with project Online-functional-test, build 1354
java.lang.NullPointerException
	at net.masterthought.cucumber.util.Util.toValidFileName(Util.java:50)
	at net.masterthought.cucumber.json.Feature.setReportFileName(Feature.java:176)
	at net.masterthought.cucumber.json.Feature.setMetaData(Feature.java:157)
	at net.masterthought.cucumber.ReportParser.setMetadata(ReportParser.java:91)
	at net.masterthought.cucumber.ReportParser.parseJsonResults(ReportParser.java:61)
	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:51)
	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:138)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:74)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:770)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:734)
	at hudson.model.Build$BuildExecution.post2(Build.java:183)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:683)
	at hudson.model.Run.execute(Run.java:1784)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:89)
	at hudson.model.Executor.run(Executor.java:240)
Trying to generate report from following files. Make sure they are valid cucumber report files:
           /var/lib/jenkins/jobs/Online-functional-test/builds/2017-01-17_11-54-49/cucumber-html-reports/cucumber.json
           /var/lib/jenkins/jobs/Online-functional-test/builds/2017-01-17_11-54-49/cucumber-html-reports/features/.cucumber/stepdefs.json**
                  

Please find below attached json files
[CucumberJson.txt](https://github.com/damianszczepanik/cucumber-reporting-jenkins/files/710167/CucumberJson.txt)
[StepdefsJson.txt](https://github.com/damianszczepanik/cucumber-reporting-jenkins/files/710166/StepdefsJson.txt)

**Comment by damianszczepanik** [comment]
This is not the most recent version

**Comment by sreedharkommi** [comment]
could you please let me know the latest version number and in Jenkins the latest version it is showing is 2.5.1.

**Comment by sreedharkommi** [comment]
The plugin manager shows the latest version as 2.5.1. I see that there is another plugin which has a slightly different ID that is "cucumber-reports" which has higher versions available. Should I be looking at this new plugin instead of the "cucumber-jvm-reports" plugin or is it a compatibility issue with the Jenkins version?

**Comment by damianszczepanik** [comment]
https://wiki.jenkins-ci.org/display/JENKINS/Cucumber+Reports+Plugin
