### ISSUE TITLE
not able to generate cucumber report through jenkins 

### ISSUE THREAD

**Issue by nalinisinghh** [damianszczepanik/cucumber-reporting-jenkins#165]
while running through jenkins getting error 

Started by user admin
Building in workspace D:\Users\nsingh\.jenkins\jobs\automation\workspace
Parsing POMs
Established TCP socket on 51271
[automation] $ D:\Java\jdk1.8.0_92/bin/java -cp D:\Users\nsingh\.jenkins\plugins\maven-plugin\WEB-INF\lib\maven33-agent-1.8.1.jar;D:\Users\nsingh\Downloads\softwares\apache-maven-3.3.9\boot\plexus-classworlds-2.5.2.jar;D:\Users\nsingh\Downloads\softwares\apache-maven-3.3.9/conf/logging jenkins.maven3.agent.Maven33Main D:\Users\nsingh\Downloads\softwares\apache-maven-3.3.9 D:\Users\nsingh\.jenkins\war\WEB-INF\lib\remoting-3.4.1.jar D:\Users\nsingh\.jenkins\plugins\maven-plugin\WEB-INF\lib\maven33-interceptor-1.8.1.jar D:\Users\nsingh\.jenkins\plugins\maven-plugin\WEB-INF\lib\maven3-interceptor-commons-1.8.1.jar 51271
<===[JENKINS REMOTING CAPACITY]===>channel started
Executing Maven:  -B -f D:\workspace\automation\pom.xml clean install
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for project:automation:jar:0.0.1-SNAPSHOT
[WARNING] 'dependencies.dependency.scope' for info.cukes:cucumber-java:jar must be one of [provided, compile, runtime, test, system] but is 'StepDefinitions.test'. @ line 11, column 20
[WARNING] 'dependencies.dependency.scope' for info.cukes:cucumber-junit:jar must be one of [provided, compile, runtime, test, system] but is 'StepDefinitions.test'. @ line 17, column 20
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building automation 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ automation ---
[INFO] Deleting D:\workspace\automation\target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ automation ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 0 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ automation ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. build is platform dependent!
[INFO] Compiling 6 source files to D:\workspace\automation\target\classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ automation ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ automation ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. build is platform dependent!
[INFO] Compiling 3 source files to D:\workspace\automation\target\test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.19:test (default-test) @ automation ---
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running runner.RunTest
Feature: verify login page
inside hook method
Starting ChromeDriver 2.24.417431 (9aea000394714d2fbb20850021f6204f2256b9cf) on port 14783
Only local connections are allowed.
log4j:WARN No appenders could be found for logger (org.apache.http.client.protocol.RequestAddCookies).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
PTC Inc. - Servigistics 11 - Sign In
user name text box is present
  @demo
  Scenario: verify login for valid user [90m# demo1.feature:3[0m
    [32mWhen [0m[32mPTC sevlistic page is open[0m     [90m# LoginStepDef.ptc_sevlistic_page_is_open()[0m
    [32mAnd [0m[32mlogin with valid usename[0m        [90m# LoginStepDef.login_with_valid_usename()[0m
    [32mThen [0m[32mUser should be login[0m           [90m# LoginStepDef.user_should_be_login()[0m

1 Scenarios ([32m1 passed[0m)
3 Steps ([32m3 passed[0m)
0m8.988s

Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 9.066 sec - in runner.RunTest

Results :

Tests run: 4, Failures: 0, Errors: 0, Skipped: 0

[JENKINS] Recording test results
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ automation ---
[INFO] Building jar: D:\workspace\automation\target\automation-0.0.1-SNAPSHOT.jar
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ automation ---
[INFO] Installing D:\workspace\automation\target\automation-0.0.1-SNAPSHOT.jar to D:\Users\nsingh\.m2\repository\project\automation\0.0.1-SNAPSHOT\automation-0.0.1-SNAPSHOT.jar
[INFO] Installing D:\workspace\automation\pom.xml to D:\Users\nsingh\.m2\repository\project\automation\0.0.1-SNAPSHOT\automation-0.0.1-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 18.592 s
[INFO] Finished at: 2017-02-07T11:08:26+05:30
[INFO] Final Memory: 25M/283M
[INFO] ------------------------------------------------------------------------
Waiting for Jenkins to finish collecting data
[JENKINS] Archiving D:\workspace\automation\pom.xml to project/automation/0.0.1-SNAPSHOT/automation-0.0.1-SNAPSHOT.pom
[JENKINS] Archiving D:\workspace\automation\target\automation-0.0.1-SNAPSHOT.jar to project/automation/0.0.1-SNAPSHOT/automation-0.0.1-SNAPSHOT.jar
channel stopped
[CucumberReport] Preparing Cucumber Reports
[CucumberReport] Copied 0 json files from workspace "D:\Users\nsingh\.jenkins\jobs\automation\workspace\target" to reports directory "D:\Users\nsingh\.jenkins\jobs\automation\builds\22\cucumber-html-reports\.cache"
ERROR: Build step failed with exception
java.lang.IllegalStateException: basedir D:\Users\nsingh\.jenkins\jobs\automation\builds\22\cucumber-html-reports\.cache does not exist.
	at org.apache.tools.ant.DirectoryScanner.scan(DirectoryScanner.java:879)
	at net.masterthought.jenkins.CucumberReportPublisher.findJsonFiles(CucumberReportPublisher.java:148)
	at net.masterthought.jenkins.CucumberReportPublisher.generateReport(CucumberReportPublisher.java:101)
	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:73)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.post2(MavenModuleSetBuild.java:1067)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
	at hudson.model.Run.execute(Run.java:1753)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:544)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:404)
Build step 'Cucumber reports' marked build as failure
Finished: FAILURE

**Comment by damianszczepanik** [comment]
ERROR: Build step failed with exception
java.lang.IllegalStateException: basedir D:\Users\nsingh.jenkins\jobs\automation\builds\22\cucumber-html-reports.cache does not exist.

**Comment by closQA** [comment]
Hi Damian,

I was wondering if there was a resolution to this? Im getting exactly the same error.

**Comment by damianszczepanik** [comment]
Should be already fixed by recent release

**Comment by satishbt** [comment]
i am using 3.18.0 version but facing the same issue.Could you please share the release where this issue is fixed
