### ISSUE TITLE
Cucumber report doesnt take variable as path

### ISSUE THREAD

**Issue by medy75** [damianszczepanik/cucumber-reporting-jenkins#167]
I am not able to use variables as path in Cucumber report plugin.
In console output you can see something like this:

> [CucumberReport] Copied 0 json files from workspace "C:\Jenkins\workspace\ZZZ-Paralel_Smoke\${ENVIRONMENT}\"${ENVIRONMENT}"\'${ENVIRONMENT}'\Project\target\Runner-Cucumber-Json"

(tried all possibilities)

**Comment by damianszczepanik** [comment]
Indeed, it does not

**Comment by damianszczepanik** [comment]
Fixed in https://github.com/jenkinsci/cucumber-reports-plugin/pull/133
