### ISSUE TITLE
404 when opening cucumber report

### ISSUE THREAD

**Issue by remcowesterhoud** [damianszczepanik/cucumber-reporting-jenkins#168]
I'm getting a 404 when trying to open the Cucumber report.

The console logs this:
```
[CucumberReportPublisher] Compiling Cucumber Html Reports ...
[CucumberReportPublisher] Copying all json files from: d:\jenkinsws\Regression-test\**\*RT.json to reports directory: D:\JenkinsHome\jobs\Regression-test\builds\2017-05-09_08-58-13\cucumber-html-reports
[CucumberReportPublisher] there were no json results found in: D:\JenkinsHome\jobs\Regression-test\builds\2017-05-09_08-58-13\cucumber-html-reports
```
The json files are created and are valid. They are sitting in an directory that matches the path mentioned. However, they do not get copied to the cucumber-html-reports folder.

**Comment by damianszczepanik** [comment]
Last line says that the report did not find any JSON file so it could not be generated

**Comment by remcowesterhoud** [comment]
It is generated, it just doesn't copy it to the folder properly

**Comment by damianszczepanik** [comment]
Then the configuration of the plugin which decide what should be copied is not proper. Leave it empty and chech which files are copied. Then tune this configuration

**Comment by remcowesterhoud** [comment]
Hmm, I tried leaving the configuration empty and now it did find my json files. However, this way it also matches with ~1000 other json files that aren't test results.

What I'm wondering is how it could find them now. Can I not use Ant naming patterns? It seems to me that **/*RT.json should be matching all files in the workspace that end on RT.json which would be all my test results.

**Comment by damianszczepanik** [comment]
https://github.com/jenkinsci/cucumber-reports-plugin/blob/master/src/main/java/net/masterthought/jenkins/CucumberReportPublisher.java should help
