### ISSUE TITLE
using pytest --cucumberjson

### ISSUE THREAD

**Issue by MonRes** [damianszczepanik/cucumber-reporting-jenkins#173]
Hi. I've got some problem with generate proper json for cucumber.
I try to use "pytest some_test.py --cucumberjson=target/cucumber.json" in declarative pipeline in jenkins. 
I receive cucumber.json file in workspace but this json include empty list "[]". 

Second way.. I created json using pytest-json plugin and than try to convert it using behave2cucumber but it also not work. I receive AtributeError that 'str' object do not have 'pop' one. 

Could you tell me what I need do configure to create proper json?

**Comment by damianszczepanik** [comment]
Not this project

**Comment by MonRes** [comment]
@damianszczepanik could you help me and tell where I can put my question?
