### ISSUE TITLE
Jenkins Build stalls at cucumber reports creation.

### ISSUE THREAD

**Issue by DineshGon** [damianszczepanik/cucumber-reporting-jenkins#181]
While running the maven build on local it works perfectly fine But where as when i ran the same build on Jenkins It Stalls at these step below.

All the Feature files runs complete at this stage. But stalls here. Below is the success scenario on local. 

**View your Cucumber Report at:                                            ?
? https://reports.cucumber.io/reports/850e6cea-46d4-4262-9d2c-9d256d748800 ?
?                                                                          ?
? This report will self-destruct in 24h.                                   ?
? Keep reports forever: https://reports.cucumber.io/profile**  

**Steps which i am performing before it stalls** 
**Running the Tests**
 
**[INFO]
[INFO] --- maven-surefire-plugin:2.18.1:test (default-test) @ dso-springboot-oci-web ---
[INFO] Surefire report directory: C:\Users\C233696\Documents\New_Laptop\2021\2.5.5_New\dso-springboot-oci-web\target\surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
15:26:07.836 [main] DEBUG org.springframework.test.context.junit4.SpringJUnit4ClassRunner - SpringJUnit4ClassRunner constructor called with [class com.aetna.java.dso.controller.HelloControllerTest]
15:26:07.880 [main] DEBUG org.springframework.test.context.BootstrapUtils - Instantiating CacheAwareContextLoaderDelegate from class [org.springframework.test.context.cache.DefaultCacheAwareContextL
oaderDelegate]**
Feature: Calculator

Scenario: Substract two numbers # src/test/resources/Calculator/AddOperations.feature:54
  Given I have a Caculator              # com.git.java.dso.demo.CalculatorSteps.i_have_a_caculator()
  When I substract 10 and 6            # com.git.java.dso.demo.CalculatorSteps.i_substract_and(long,long)
  Then The result should be 4          # com.git.java.dso.demo.CalculatorSteps.the_result_should_be(long)

Scenario: Substract two numbers # src/test/resources/Calculator/AddOperations.feature:54
  Given I have a Caculator              # com.git.java.dso.demo.CalculatorSteps.i_have_a_caculator()
  When I substract 10 and 5            # com.git.java.dso.demo.CalculatorSteps.i_substract_and(long,long)
  Then The result should be 5          # com.git.java.dso.demo.CalculatorSteps.the_result_should_be(long)

Expected ::
Jenkins Build Stalls
Actual:: 
**View your Cucumber Report at:                                            ?
? https://reports.cucumber.io/reports/850e6cea-46d4-4262-9d2c-9d256d748800 ?
?                                                                          ?
? This report will self-destruct in 24h.                                   ?
? Keep reports forever: https://reports.cucumber.io/profile**

**Comment by damianszczepanik** [comment]
This refers to cucumber.io not this plugin

**Comment by DineshGon** [comment]
**Solution** 
under the **src/test/resources** folder create the **cucumber.properties** file and add the below line. 
**cucumber.publish.enabled =false
cucumber.publish.quiet =true**
