### ISSUE TITLE
NullPointer when generating HTML report

### ISSUE THREAD

**Issue by jeremyGoupil** [damianszczepanik/cucumber-reporting-jenkins#2]
Hi,

I have this little problem : 

[CucumberReportPublisher] Compiling Cucumber Html Reports ...
[CucumberReportPublisher] copying json to reports directory: /data/jenkins/jobs/test-modules-cucumber-jvm/builds/2012-04-25_17-21-39/cucumber-html-reports
[CucumberReportPublisher] Generating HTML reports
ERROR: Publisher net.masterthought.jenkins.CucumberReportPublisher aborted due to exception
java.lang.NullPointerException
    at net.masterthought.jenkins.FeatureReportGenerator.getAllStepStatuses(FeatureReportGenerator.java:131)
    at net.masterthought.jenkins.FeatureReportGenerator.<init>(FeatureReportGenerator.java:29)
    at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:71)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:19)
    at hudson.model.AbstractBuild$AbstractRunner.perform(AbstractBuild.java:692)
    at hudson.model.AbstractBuild$AbstractRunner.performAllBuildSteps(AbstractBuild.java:667)
    at hudson.maven.MavenModuleSetBuild$RunnerImpl.post2(MavenModuleSetBuild.java:989)
    at hudson.model.AbstractBuild$AbstractRunner.post(AbstractBuild.java:614)
    at hudson.model.Run.run(Run.java:1429)
    at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:478)
    at hudson.model.ResourceController.execute(ResourceController.java:88)
    at hudson.model.Executor.run(Executor.java:230)

Could you help ?

I try to fork and correct this by my self but when I try to build I obtain that :

[INFO] Failed to resolve artifact.
## Missing:

1) org.kohsuke.stapler:stapler-groovy:jar:1.169

  Try downloading the file manually from the project website.

  Then, install it using the command: 
      mvn install:install-file -DgroupId=org.kohsuke.stapler -DartifactId=stapler-groovy -Dversion=1.169 -Dpackaging=jar -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there: 
      mvn deploy:deploy-file -DgroupId=org.kohsuke.stapler -DartifactId=stapler-groovy -Dversion=1.169 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency: 
    1) org.jenkins-ci.tools:maven-hpi-plugin:maven-plugin:1.74
    2) org.kohsuke.stapler:stapler-groovy:jar:1.169

2) org.kohsuke.stapler:stapler-jelly:jar:1.169

  Try downloading the file manually from the project website.

  Then, install it using the command: 
      mvn install:install-file -DgroupId=org.kohsuke.stapler -DartifactId=stapler-jelly -Dversion=1.169 -Dpackaging=jar -Dfile=/path/to/file

  Alternatively, if you host your own repository you can deploy the file there: 
      mvn deploy:deploy-file -DgroupId=org.kohsuke.stapler -DartifactId=stapler-jelly -Dversion=1.169 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]

  Path to dependency: 
    1) org.jenkins-ci.tools:maven-hpi-plugin:maven-plugin:1.74
    2) org.kohsuke.stapler:stapler-groovy:jar:1.169
    3) org.kohsuke.stapler:stapler-jelly:jar:1.169

---

2 required artifacts are missing.

for artifact: 
  org.jenkins-ci.tools:maven-hpi-plugin:maven-plugin:1.74

from the specified remote repositories:
  public (http://mvnrepository.adencf.local/nexus/content/groups/public),
  repo.jenkins-ci.org (http://repo.jenkins-ci.org/public/),
  central (http://repo1.maven.org/maven2),
  sonatype-snapshots (https://oss.sonatype.org/content/repositories/snapshots),
  public-snapshots (http://mvnrepository.adencf.local/nexus/content/groups/public-snapshots)

**Comment by ChaitanyaChannella** [comment]
I'm having a similar issue,m here is what I get in the console output

[CucumberReportPublisher] Compiling Cucumber Html Reports ...
[CucumberReportPublisher] copying all json files from slave: /var/jenkins/workspace/Allure_test_job to master reports directory: /var/lib/jenkins/jobs/Allure_test_job/builds/2015-01-23_15-51-16/cucumber-html-reports
[CucumberReportPublisher] Found the following number of json files: 1
[CucumberReportPublisher] 0. Found a json file: results.json
[CucumberReportPublisher] Generating HTML reports
[CucumberReportPublisher] there was an error generating the reports: java.lang.NullPointerException
net.masterthought.cucumber.ReportBuilder.getBuildStatus(ReportBuilder.java:76)
net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:112)
hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:770)
hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:734)
hudson.model.Build$BuildExecution.post2(Build.java:183)
hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:683)
hudson.model.Run.execute(Run.java:1784)
hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
hudson.model.ResourceController.execute(ResourceController.java:89)
hudson.model.Executor.run(Executor.java:240)

I would appreciate any ideas or suggestions

**Comment by JimFung** [comment]
@ChaitanyaChannella I am running into the same issue, did you ever find a fix for it?

**Comment by damianszczepanik** [comment]
Upgrade the plugin

**Comment by JimFung** [comment]
@damianszczepanik updating the plugin fixed it. thanks

**Comment by sunilkandakatla** [comment]
Hi Can You help on this.

Error
Something went wrong with project master, build 140

java.lang.NullPointerException
Trying to generate report from following files. Make sure they are valid cucumber report files:
           /var/lib/jenkins/jobs/REST-Digital/jobs/cc-account-pin/branches/master/builds/140/cucumber-html-reports/.cache/cucumber.json
           /var/lib/jenkins/jobs/REST-Digital/jobs/cc-account-pin/branches/master/builds/140/cucumber-html-reports/.cache/features/config/change-mail-digital/CanChipCards.json
           /var/lib/jenkins/jobs/REST-Digital/jobs/cc-account-pin/branches/master/builds/140/cucumber-html-reports/.cache/features/config/change-mail-digital/CanNonChipCards.json
           /var/lib/jenkins/jobs/REST-Digital/jobs/cc-account-pin/branches/master/builds/140/cucumber-html-reports/.cache/features/config/change-mail-digital/USChipCards.json
           /var/lib/jenkins/jobs/REST-Digital/jobs/cc-account-pin/branches/master/builds/140/cucumber-html-reports/.cache/features/config/change-mail-digital/USNonChipCards.json
           /var/lib/jenkins/jobs/REST-Digital/jobs/cc-account-pin/branches/master/builds/140/cucumber-html-reports/.cache/features/config/change-mail-digital/new.json
           /var/lib/jenkins/jobs/REST-Digital/jobs/cc-account-pin/branches/master/builds/140/cucumber-html-reports/.cache/features/config/mail-digital/CanChipCards.json
           /var/lib/jenkins/jobs/REST-Digital/jobs/cc-account-pin/branches/master/builds/140/cucumber-html-reports/.cache/features/config/mail-digital/CanNonChipCards.json
           /var/lib/jenkins/jobs/REST-Digital/jobs/cc-account-pin/branches/master/builds/140/cucumber-html-reports/.cache/features/config/mail-digital/USChipCards.json
           /var/lib/jenkins/jobs/REST-Digital/jobs/cc-account-pin/branches/master/builds/140/cucumber-html-reports/.cache/features/config/mail-digital/USNonChipCards.json
           /var/lib/jenkins/jobs/REST-Digital/jobs/cc-account-pin/branches/master/builds/140/cucumber-html-reports/.cache/features/config/mail-digital/new.json
