### ISSUE TITLE
json reports directory being ignored on slave

### ISSUE THREAD

**Issue by dpayne** [damianszczepanik/cucumber-reporting-jenkins#27]
The setting for json report directory is ignored when the plugin is running on a slave.

Specifically in CucumberReportPublisher the line
```java
    projectWorkspaceOnSlave.copyRecursiveTo( "**/*.json","", masterJsonReportDirectory);
```

does not include the jsonReportDirectory in the path if it is not empty.

it should be changed to something like the following
```java
if (jsonReportDirectory.isEmpty()) {
       projectWorkspaceOnSlave = new FilePath(projectWorkspaceOnSlave, jsonReportDirectory);
       projectWorkspaceOnSlave.copyRecursiveTo( "**/*.json","", masterJsonReportDirectory);
} else {
       projectWorkspaceOnSlave.copyRecursiveTo( "**/*.json","", masterJsonReportDirectory);
}

```

Note: I have not yet tested the above code snippet

**Comment by damianszczepanik** [comment]
This code has been refactored recently so take a look and check with the most recent version
