### ISSUE TITLE
404 error when accessing Cucumber Reports

### ISSUE THREAD

**Issue by winterkid** [damianszczepanik/cucumber-reporting-jenkins#28]
Hello,

i'm running cucumber-reports 0.0.14 on a Jenkins 1.473
When accessing the reports of project foo i get a page with a 404 error. And the console output your plugin during the build is:
...
[CucumberReportPublisher] Compiling Cucumber Html Reports ...
[CucumberReportPublisher] detected this build is running on the master 
[CucumberReportPublisher] copying json to reports directory: /proj/bar/tools/hudson/jobs/foo/builds/2012-07-29_22-00-37/cucumber-html-reports
[CucumberReportPublisher] Generating HTML reports
ERROR: Publisher net.masterthought.jenkins.CucumberReportPublisher aborted due to exception
java.lang.NullPointerException
    at net.masterthought.cucumber.util.Util.collectSteps(Util.java:104)
    at net.masterthought.cucumber.json.Element.getStatus(Element.java:31)
    at net.masterthought.cucumber.ReportInformation.processFeatures(ReportInformation.java:184)
    at net.masterthought.cucumber.ReportInformation.<init>(ReportInformation.java:37)
    at net.masterthought.cucumber.ReportBuilder.<init>(ReportBuilder.java:32)
    at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:98)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:19)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:717)
    at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:692)
    at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.post2(MavenModuleSetBuild.java:994)
    at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:639)
    at hudson.model.Run.execute(Run.java:1513)
    at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:477)
    at hudson.model.ResourceController.execute(ResourceController.java:88)
    at hudson.model.Executor.run(Executor.java:236)
Finished: FAILURE

The Json reports path is set to foo/fooweb/target. And the workspace URL in jenkins is http://localhost:8120/job/foo/ws/. All Json reports are generated into http://localhost:8120/job/foo/ws/foo/fooweb/target/ as expected. Thus everything seems perfect but still goes wrong.

Any hints or clues are appreciated.

Thomas

**Comment by vidyasris** [comment]
Can someone let me know, why i get the following error?
HTTP ERROR 404

Problem accessing /job/ParentandCarer_Test_scripts/29/cucumber-html-reports/. Reason:

    Not Found.

also, my console output says the following below, though the test script passes, there are no steps seen in the result. and also the cucumber reports gives error. 

Started by user 
Building in workspace C:\Program Files (x86)\Jenkins\workspace\ParentandCarer_Test_scripts
 > C:\Program Files (x86)\Git\bin\git rev-parse --is-inside-work-tree
Fetching changes from the remote Git repository
 > C:\Program Files (x86)\Git\bin\git config remote.origin.url https://bitbucket.org/enterpriseapps/parentandcarer_testscript.git
Fetching upstream changes from https://bitbucket.org/enterpriseapps/parentandcarer_testscript.git
 > C:\Program Files (x86)\Git\bin\git --version
using .gitcredentials to set credentials
 > C:\Program Files (x86)\Git\bin\git config --local credential.helper store --file=\"C:\Users\SVC-AD~1\AppData\Local\Temp\git5050885723921518410.credentials\"
 > C:\Program Files (x86)\Git\bin\git fetch --tags --progress https://bitbucket.org/enterpriseapps/parentandcarer_testscript.git +refs/heads/*:refs/remotes/origin/*
 > C:\Program Files (x86)\Git\bin\git config --local --remove-section credential
Seen branch in repository origin/master
Seen 1 remote branch
Checking out Revision 2bc7bee6aabd462724ace69c08b645746f49b713 (origin/master)
 > C:\Program Files (x86)\Git\bin\git config core.sparsecheckout
 > C:\Program Files (x86)\Git\bin\git checkout -f 2bc7bee6aabd462724ace69c08b645746f49b713
 > C:\Program Files (x86)\Git\bin\git rev-list 68f0844f70cae05a37f75914114aeb26d6c1d0a3
 > C:\Program Files (x86)\Git\bin\git tag -a -f -m Jenkins Build #29 jenkins-ParentandCarer_Test_scripts-29
[ParentandCarer_Test_scripts] $ cmd /c call C:\Users\SVC-AD~1\AppData\Local\Temp\hudson7583128657053000735.bat

C:\Program Files (x86)\Jenkins\workspace\ParentandCarer_Test_scripts>taskkill /F /IM chrome.exe 
ERROR: The process "chrome.exe" not found.

C:\Program Files (x86)\Jenkins\workspace\ParentandCarer_Test_scripts>taskkill /F /IM conhost.exe 
SUCCESS: The process "conhost.exe" with PID 1700 has been terminated.

C:\Program Files (x86)\Jenkins\workspace\ParentandCarer_Test_scripts>exit 0 
[ParentandCarer_Test_scripts] $ C:\Ruby193\bin\rake.bat features
[htmlpublisher] Archiving HTML reports...
[CucumberReportPublisher] Compiling Cucumber Html Reports ...
[CucumberReportPublisher] detected this build is running on the master 
[CucumberReportPublisher] there were no json results found in: C:\Program Files (x86)\Jenkins\workspace\ParentandCarer_Test_scripts
[CucumberReportPublisher] there were no json results found in: C:\Program Files (x86)\Jenkins\jobs\ParentandCarer_Test_scripts\builds\29\cucumber-html-reports
Finished: SUCCESS

**Comment by kingsleyh** [comment]
Looks like no cucumber json file was found so report wasn't generated.

Check that the cucumber json is being correctly generated in the place you expect

**Comment by Tester-Sri** [comment]
Thanks, I have now created the files. in the location - but my file is empty. and the cucumber report is as below, am i missing something?

Feature Statistics

Feature	Scenarios	Steps	Passed	Failed	Skipped	Pending	Duration	Status
0	0	0	0	0	0	0	0 ms	Totals

Started by user 
Building in workspace C:\Program Files (x86)\Jenkins\workspace\ParentandCarer_Test_scripts
 > C:\Program Files (x86)\Git\bin\git rev-parse --is-inside-work-tree
Fetching changes from the remote Git repository
 > C:\Program Files (x86)\Git\bin\git config remote.origin.url https://bitbucket.org/enterpriseapps/parentandcarer_testscript.git
Fetching upstream changes from https://bitbucket.org/enterpriseapps/parentandcarer_testscript.git
 > C:\Program Files (x86)\Git\bin\git --version
using .gitcredentials to set credentials
 > C:\Program Files (x86)\Git\bin\git config --local credential.helper store --file=\"C:\Users\SVC-AD~1\AppData\Local\Temp\git5428559279904858741.credentials\"
 > C:\Program Files (x86)\Git\bin\git fetch --tags --progress https://bitbucket.org/enterpriseapps/parentandcarer_testscript.git +refs/heads/*:refs/remotes/origin/*
 > C:\Program Files (x86)\Git\bin\git config --local --remove-section credential
Seen branch in repository origin/master
Seen 1 remote branch
Checking out Revision 728ab084e47ab35e7370dba1a15161751351373a (origin/master)
 > C:\Program Files (x86)\Git\bin\git config core.sparsecheckout
 > C:\Program Files (x86)\Git\bin\git checkout -f 728ab084e47ab35e7370dba1a15161751351373a
 > C:\Program Files (x86)\Git\bin\git rev-list 2bc7bee6aabd462724ace69c08b645746f49b713
 > C:\Program Files (x86)\Git\bin\git tag -a -f -m Jenkins Build #34 jenkins-ParentandCarer_Test_scripts-34
[ParentandCarer_Test_scripts] $ cmd /c call C:\Users\SVC-AD~1\AppData\Local\Temp\hudson179901555023620916.bat

C:\Program Files (x86)\Jenkins\workspace\ParentandCarer_Test_scripts>taskkill /F /IM chrome.exe 
ERROR: The process "chrome.exe" not found.

C:\Program Files (x86)\Jenkins\workspace\ParentandCarer_Test_scripts>taskkill /F /IM conhost.exe 
SUCCESS: The process "conhost.exe" with PID 6704 has been terminated.

C:\Program Files (x86)\Jenkins\workspace\ParentandCarer_Test_scripts>exit 0 
[ParentandCarer_Test_scripts] $ C:\Ruby193\bin\rake.bat features
[htmlpublisher] Archiving HTML reports...
[CucumberReportPublisher] Compiling Cucumber Html Reports ...
[CucumberReportPublisher] detected this build is running on the master 
[CucumberReportPublisher] copying json to reports directory: C:\Program Files (x86)\Jenkins\jobs\ParentandCarer_Test_scripts\builds\34\cucumber-html-reports
[CucumberReportPublisher] Generating HTML reports
Finished: SUCCESS

**Comment by kingsleyh** [comment]
Does your cucumber.json have valid content?

**Comment by Tester-Sri** [comment]
Teh cucumber.json file is empty, should i fill with the contents, or it gets autogenerated?

**Comment by kingsleyh** [comment]
It gets auto generated by cucumber when you set the option in the cucumber runner to produce the json - in the runner

**Comment by Tester-Sri** [comment]
<CUCUMBER_RUN_CONFIG_SETTINGS_ID NAME="CUCUMBER_RUNNER_PATH" VALUE="" />
      <CUCUMBER_RUN_CONFIG_SETTINGS_ID NAME="USE_CUSTOM_RUNNER" VALUE="false" />
      <CUCUMBER_RUN_CONFIG_SETTINGS_ID NAME="SETTINGS_VERSION" VALUE="2" />

I have specified these values in the workspace.xml file, still everytime, the build is successful, but there is no report generated or it is empty. No feature/scenario steps are displayed in the console output?

**Comment by kingsleyh** [comment]
You need to specify the json formatter somewhere

**Comment by Tester-Sri** [comment]
I specified, but still not able to get the features and scenarios in the console output.. the test always passes, but never says, how many features and scenarios are passed in the console output in jenkins, can you please help?

**Comment by kingsleyh** [comment]
I think your cucumber configuration does not specify a json formatter so you are not getting a cucumber json file - the Jenkins report needs a cucumber json file to work

**Comment by Tester-Sri** [comment]
now, it is working, but still, it doesnt actually execute the scenarios, it doesnt give the print 'puts' statement messages, once the scenario has passed? any ideas why?

ParentandCarer_Test_scripts] $ C:\Ruby193\bin\rake.bat features
*** WARNING: You must use ANSICON 1.31 or higher (https://github.com/adoxa/ansicon/) to get coloured output on Windows
C:/Ruby193/bin/ruby -S bundle exec cucumber features --tags ~@login --format pretty --format json --out reports/cucumber_results.json
*** WARNING: You must use ANSICON 1.31 or higher (https://github.com/adoxa/ansicon/) to get coloured output on Windows
Feature: Booking
  As a User
  I can book the parking

  Scenario: User Booking                                    # features\booking.feature:15
    Given Iam in Parentsparkingpermit page                  # features/step_definitions/booking.rb:2
    When I enter "test1" into vehicle registration number # features/step_definitions/booking.rb:7
    When I select car park id                               # features/step_definitions/booking.rb:29
    When I click on book button                             # features/step_definitions/booking.rb:49
    Then I should see Booking confirmation  page            # features/step_definitions/booking.rb:76

Feature: Login
  As a User
  I can login to the Parents Parking application

  Scenario: User login                                                                       # features\login.feature:5
    Given Iam in ParentsParking Login page                                                   # features/step_definitions/login.rb:1
    When I enter "username" into field having id "ctl00_ContentPlaceHolder1_UsernameTextBox"    # features/step_definitions/login.rb:5
    And I enter "Password" into input having id "ctl00_ContentPlaceHolder1_PasswordTextBox" # features/step_definitions/login.rb:9
    And I click on element with name "Sign In"                                               # features/step_definitions/login.rb:13
    Then I should see Parentsparkingpermit page                                              # features/step_definitions/login.rb:17

2 scenarios (2 passed)
10 steps (10 passed)
0m30.236s
[htmlpublisher] Archiving HTML reports...
[CucumberReportPublisher] Compiling Cucumber Html Reports ...
[CucumberReportPublisher] detected this build is running on the master 
[CucumberReportPublisher] copying json to reports directory: C:\Program Files (x86)\Jenkins\jobs\ParentandCarer_Test_scripts\builds\37\cucumber-html-reports
[CucumberReportPublisher] Generating HTML reports

Finished: SUCCESS
 Help us localize this page

**Comment by seleniumbheema** [comment]
I'm facing the same issue

**Comment by ssatyacc** [comment]
Hi,

I am configuring jenkins for my Android Application and I am facing the 404 error with the error
Problem accessing /job/zimmber%20client%20app/build. Reason:

The url seems to work when a user is logged in and is throwing 404 when the user is logged out.
Please tell me what configs I could have configured wrong

**Comment by ArcSaikat** [comment]
I am having the similar issue. I have cucumber.html & cucumber.json generated in the project folder after test execution completed. But in jenkins cucumber plugin URL, having below errors:  

HTTP ERROR 404
Problem accessing /job/amazon_smoke_build/8/cucumber-html-reports/. Reason:
Not Found
Powered by Jetty://

How can i explicitly set up the report path in jenkins ????
