### ISSUE TITLE
Feature Result report page is inaccurate

### ISSUE THREAD

**Issue by divyaA** [damianszczepanik/cucumber-reporting-jenkins#34]
We have multi module mvn project.

And we have several .feature files in each module. And the test runners are set up to create separate .json file for each test run like below. 

@RunWith(Cucumber.class)
@Cucumber.Options(features = {"classpath:cucumberDefect1.feature"}, format = {"pretty", "html:target/cucumber", "son:target/cucumber1.json"})
public class cucumberDefect1 {
}

@RunWith(Cucumber.class)
@Cucumber.Options(features = {"classpath:cucumberDefect2.feature"}, format = {"pretty", "html:target/cucumber", "son:target/cucumber2.json"})
public class cucumberDefect2 {
}

We run these tests on Jenkins with the cucumber plugin to generate the cucumber reports. And we run these tests in parallel on multiple threads so the build run time is minimized. 

Some of the cucumber reports generated are incorrect. The Feature Statistics report seems fine. But when clicked on a feature link to view Feature Result, it always takes us to the last feature that was run in the set.  

Below is how I would put the current behavior:

Given n test feature files in a multi-module maven project
And these test feature files are run in parallel on CI
And nth feature file is the last one to be run in the set
And CI has produced the cucumber report
When clicked on any feature link other than the nth to view the Feature Result page
Then the viewer is rendered with Feature Results page of the nth feature
And not the correct features Feature Result page

Below is the behavior we would like to have:

Given n test feature files in a multi-module maven project
And the these test feature files are run in parallel on CI
And nth feature file is the last one to be run in the set
And CI has produced the cucumber report
When clicked on n-1feature link to view the Feature Result page
Then the viewer is rendered with Feature Results page of n-1 feature
And not Feature Results page of the nth feature 

The 0.0.10 is the plugin version we have.

**Comment by damianszczepanik** [comment]
Try with the most recent version, should be fixed
