### ISSUE TITLE
"Back to Jenkins" link broken

### ISSUE THREAD

**Issue by stevenkb** [damianszczepanik/cucumber-reporting-jenkins#46]
The "Back to Jenkins" link at the top of each page assumes that Jenkins is installed on the root of the web server.

My instance of Jenkins is installed at _http://server/jenkins_, therefore the "Back to Jenkins" link should be:
_http://server/jenkins/job/project_name/build_number_
however, the link currently is:
_http://server/job/project_name/build_number_

Interestingly enough, the other links are all correct and direct me to the right location (taking into account my "jenkins" subfolder), it's just the "Back to Jenkins" link that is broken.

**Comment by boly38** [comment]
@stevenkb please could you tell how to set this variable ?
