### ISSUE TITLE
CucumberReportPublisher   - Jenkins  - Taking long time "Generating HTML reports".... basically timeout and breaks the build

### ISSUE THREAD

**Issue by surendrakashyap** [damianszczepanik/cucumber-reporting-jenkins#59]
JENKINS] Archiving /apps/Jenkins-Slave/workspace/rps-bs-target-ws-1.0/target/rps_bs_ts_ws-1.0.0.0-SNAPSHOT-sources.jar to /views/Hudson_WRK_Area/jobs/rps-bs-target-ws-1.0/modules/com.jpmorgan.rps$rps_bs_ts_ws/builds/2013-04-30_11-40-20/archive/com.jpmorgan.rps/rps_bs_ts_ws/1.0.0.0-20130430.155043-194/rps_bs_ts_ws-1.0.0.0-20130430.155043-194-sources.jar
[JENKINS] Archiving /apps/Jenkins-Slave/workspace/rps-bs-target-ws-1.0/target/rps_bs_ts_ws-1.0.0.0-SNAPSHOT-javadoc.jar to /views/Hudson_WRK_Area/jobs/rps-bs-target-ws-1.0/modules/com.jpmorgan.rps$rps_bs_ts_ws/builds/2013-04-30_11-40-20/archive/com.jpmorgan.rps/rps_bs_ts_ws/1.0.0.0-20130430.155043-194/rps_bs_ts_ws-1.0.0.0-20130430.155043-194-javadoc.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESSFUL
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14 minutes 48 seconds
[INFO] Finished at: Tue Apr 30 11:55:24 EDT 2013
[INFO] Final Memory: 181M/795M
[INFO] ------------------------------------------------------------------------
channel stopped
[CucumberReportPublisher] Compiling Cucumber Html Reports ...
[CucumberReportPublisher] detected this build is running on a slave 
[CucumberReportPublisher] copying json from: file:/apps/Jenkins-Slave/workspace/rps-bs-target-ws-1.0/to reports directory: file:/views/Hudson_WRK_Area/jobs/rps-bs-target-ws-1.0/builds/2013-04-30_11-40-14/cucumber-html-reports/
[CucumberReportPublisher] Generating HTML reports

**** No additional on server!

**Comment by damianszczepanik** [comment]
I expect that this might be a problem and it may take time when the report is so big.

I'm also afraid that it would be a challenge to fix it without such report.

**Comment by damianszczepanik** [comment]
Similar https://github.com/damianszczepanik/cucumber-reporting/issues/122
