### ISSUE TITLE
Multiple Screenshots : Second screenshot doesn't expand when clicked on the first one initially

### ISSUE THREAD

**Issue by DhanjeetJadeja** [damianszczepanik/cucumber-reporting-jenkins#62]
When you have multiple screenshots on your report and you have initially clicked on one of them, scrolling and clicking on the next one will not collapse the first and open the current(clicked) screenshot.

*Steps to Reproduce*

1. Go to a report which has multiple features which failed and has screenshots attached.
2. Click on the first screenshot link (it will expand)
3. Scroll to the next screenshot link and click it

Expected
The second screenshot should expand. Collapsing the first one is optional.

Actual
The page seems as if it moved, but the second screenshot doesn't expand, the first remains as is.

**Comment by damianszczepanik** [comment]
Released
