### ISSUE TITLE
jenkins-cucumber-jvm-reports-plugin issue with "Background:" step in a feature file

### ISSUE THREAD

**Issue by 3Thomson14** [damianszczepanik/cucumber-reporting-jenkins#76]
The Json output file generated with Cucumber Json formatter including test results for "Background:" step separately even though it is mentioned as test step  "Scenario:". So "Background:" test step doesn't have any "status": due to which Report generated by Cucumber Jvm plugin from json output file to Skipped due to no result status.

So how to skip jenkins-cucumber-jvm-reports-plugin not to Look at "Background" test step while generating the reports?

Below is Json Out put for one test example.

"Background:"

"elements":[
         {
            "name":"",
            "keyword":"Background",
            "description":"",
            "type":"background",
            "line":23,
            "steps":[
               {
                  "name":"I have opened the Share Document pop-up dialog box for document \"xyz\"",
                  "line":24,
                  "keyword":"Given "
               }
            ]
         }

Scenario:

 "steps":[
               {
                  "name":"I have opened the Share Document pop-up dialog box for document \"xyz\"",
                  "line":24,
                  "keyword":"Given ",
                  "result":{
                     "status":"passed"
                  },
                  "match":{

                  }
               }

**Comment by damianszczepanik** [comment]
Should be fixed with newer version
