### ISSUE TITLE
UTF-8 Character parsing error & Broken output

### ISSUE THREAD

**Issue by SeungBeomChoi** [damianszczepanik/cucumber-reporting-jenkins#77]
I wrote cucumber feature in Korean.
This plug-in works Run cucumber -> json output -> generate html

But in my json (cucumber output),

1. some string can't parse
 original text in json :  "name": "가져온 상품주문번호 상품을 \"EXCHANGE_PRODUCT_READY\" 사유와 \"교환 준비중이니 기다리세요\" 상세사유로 교환 보류 처리한다",
 error message : com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 2222 column 99

2. broken UTF-8 text
![2013-10-11 2 14 39](https://f.cloud.github.com/assets/5661528/1312377/18efb696-3234-11e3-8bf6-2a80c21ccfb7.png)

**Comment by damianszczepanik** [comment]
Should be fixed with newer version
