### ISSUE TITLE
Test formatting of background

### ISSUE THREAD

**Issue by thestumonkey** [damianszczepanik/cucumber-reporting-jenkins#78]
It seems the report lists the background step for all scenarios.  I don't really need it to read the background for each test, at the least it should be collapsed.
Currently it's difficult to read as the separation between scenarios is not very visible
![screen shot 2013-10-21 at 9 32 42 pm](https://f.cloud.github.com/assets/435874/1378627/ed16ed16-3ad3-11e3-81c6-ae9f2b09ea81.png)

**Comment by damianszczepanik** [comment]
Should be fixed with newer version
