### ISSUE TITLE
Tags are not parsed correctly

### ISSUE THREAD

**Issue by meredrica** [damianszczepanik/cucumber-reporting-jenkins#80]
I have a few scenarios that are marked with `@passing`
The generated HTML site shows some of those steps as failing. The problem is that the scenarios below a `@passing` step are also considered to be marked with this tag (they are not tagged). This makes the tag view unusable. I also checked the generated json, it's correct.

I use a recently manually compiled jar from here.

**Comment by damianszczepanik** [comment]
If problem still remain, attach json file
