### ISSUE TITLE
Add the option to mark Jenkins build as Unstable rather than Failed if a cucumber test fails

### ISSUE THREAD

**Issue by simonstringer** [damianszczepanik/cucumber-reporting-jenkins#81]
In Jenkins (at least the way I have configured it) if a unit test fails, it marks the job as unstable. I'd like the option to mark the job as unstable if a cucumber test fails.

Currently I have 4 types of test, 3 of them mark the job as unstable if they fail. A failing Cucumber test marks the job as failed, where I believe it should behave the same as the other 3 types of test. (Or at least be an option)

**Comment by damianszczepanik** [comment]
You can configure build result based on cucumber results
