### ISSUE TITLE
Cucumber report in Jenkins not showing line break between scenario.write

### ISSUE THREAD

**Issue by K76154** [damianszczepanik/cucumber-reporting-jenkins#82]
I have some custom log entries that I add during my test using scenario.write. Those displays without problem in cucumber HTML report. However, when in JSON format and then parsed by the Jenkins cucumber report plugin, those custom log entries does not have the line break between lines. That makes them really hard to read.

**Comment by mylene** [comment]
Just use plain html (<p></p> or <br />) tags. Works like a charm.

**Comment by damianszczepanik** [comment]
Custom logs have been improved recently but if you still have problem, attach JSON file so I can work on this
