### ISSUE TITLE
Background activity counting as scenario in reports

### ISSUE THREAD

**Issue by avshah88** [damianszczepanik/cucumber-reporting-jenkins#85]
This plugin seems to counting background activity from feature file as scenarios. I ran a feature file containing 2 scenarios each having a "Background" activity. In the generated report I see total of 4 scenarios passed. Is there any way to show the count of scenarios excluding background activities?

Thanks.

**Comment by damianszczepanik** [comment]
Currently backgrounds are not counted. Try to upgrade
