### ISSUE TITLE
doc_string in expected result nog shown in report

### ISSUE THREAD

**Issue by anoordover** [damianszczepanik/cucumber-reporting-jenkins#88]
When I have a test-step that has a multi-line parameter this parameter doesn't show up on the html report.
This is part of the json report.

{
            "result": {
              "duration": 956574,
              "status": "passed"
            },
            "name": "zou het retourbestand in \"belastingdienst/uitgaand/outbox\" de volgende inhoud moeten hebben:",
            "keyword": "Dan ",
            "line": 47,
            "doc_string": {
              "value": "first line\nsecond line\n",
              "line": 48,
              "content_type": ""
            },
            "match": {
              "arguments": [
                {
                  "val": "belastingdienst/uitgaand/outbox",
                  "offset": 26
                }
              ],
              "location": "StepDefinitionsBestanden.controleerInhoudVanRetourbestand(String,String)"
            }
          }

I use version 0.0.21 of the reporting plugin and cucumber-java version  1.1.5

**Comment by damianszczepanik** [comment]
Reference https://cucumber.io/docs/reference#doc-strings

**Comment by damianszczepanik** [comment]
doc_string is supported now
