### ISSUE TITLE
Scenarios run repeatedly not differentiated in reports?

### ISSUE THREAD

**Issue by millarm** [damianszczepanik/cucumber-reporting-jenkins#89]
We are running a setup where the same test suite is re-run multiple times on the same build - on different iOS versions (iOS 7.0, iOS 6.1 and iOS 6.0)

Cucumber reporting doesn't differentiate between these when linking to the individual feature reports - the "Smoke test" report linked to is the same one - in spite of the fact it's been generated from 3 separate and different .json files

Test numbers are correct - they reflect the individual items, it's the link through to the detailed report "smote-test.feature.html" that's the same file - only one is generated.

Have we misconfigured something, or is this not supported?

**Comment by damianszczepanik** [comment]
Should work with last release
