### ISSUE TITLE
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException when opening the report

### ISSUE THREAD

**Issue by ambirag** [damianszczepanik/cucumber-reporting-jenkins#90]
using: ruby/cucumber, generating report as mentioned in the readme, path is configured correctly as well.
But when i click the report, i get the following error:
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2

My json file starts like this
[{"keyword":"Feature","name":"

**Comment by damianszczepanik** [comment]
No feedback so far so I suppose problem is fixed :)

**Comment by anupshahgit** [comment]
Hi I am using ruby cucumber out put to generate cucumber report from jenkins. But i am getting same error.
Could you please let me know what i required to resolve this error.

cucumber-reports : 1.2.0
JDK : 1.6.15

**Comment by damianszczepanik** [comment]
Attach json file

**Comment by anupshahgit** [comment]
[cucumber.txt](https://github.com/damianszczepanik/cucumber-reporting-jenkins/files/110708/cucumber.txt)

Please check json file.

**Comment by damianszczepanik** [comment]
I've tried to validate this file wigh https://jsonformatter.curiousconcept.com/ and it says that the file is not valid at all.
But anyway this should be fixed in https://github.com/damianszczepanik/cucumber-reporting/pull/316

**Comment by anupshahgit** [comment]
Hi

Thanks for your reply.
Could you please let me know if this issue got fix then which version should i download for this fix. 

Current version is : cucumber-reports : 1.2.0

Please check updated json below. Please let me know if any other things you require.

[report.txt](https://github.com/damianszczepanik/cucumber-reporting-jenkins/files/111766/report.txt)

**Comment by anupshahgit** [comment]
Hi damian ,

Could you please check updated jason and let me know is it work with your latest cucumber report build version.
