### ISSUE TITLE
Cucumber Feature Statistics pending number of test does not show correctly 

### ISSUE THREAD

**Issue by sikamedia** [damianszczepanik/cucumber-reporting-jenkins#93]
![featurestatisticsbugreport](https://cloud.githubusercontent.com/assets/1304031/2547980/9214e596-b65a-11e3-86bc-228a5102361e.png)

Hi,

Please have a look at the attached screenshot. I have a "Predicates for sparql lib" feature test contains 7 steps, 5 passed in the test, it should report 2 pendings in fact. But the report only shows 0.

Br/Tao

**Comment by damianszczepanik** [comment]
Can you reproduce this problem with new version?
