### ISSUE TITLE
Gherkin parsing Error on report generation for scenario that uses data iteration

### ISSUE THREAD

**Issue by jovistruck** [damianszczepanik/cucumber-reporting-jenkins#95]
## Error in jenkins console
[Cucumber Tests] Parsing results.
[Cucumber Tests] parsing cucumber.json
ERROR: Publisher org.jenkinsci.plugins.cucumber.jsontestsupport.CucumberTestResultArchiver aborted due to exception
java.lang.NullPointerException
	at org.jenkinsci.plugins.cucumber.jsontestsupport.GherkinCallback.before(GherkinCallback.java:220)
	at gherkin.JSONParser.before(JSONParser.java:82)
	at gherkin.JSONParser.parse(JSONParser.java:48)
	at org.jenkinsci.plugins.cucumber.jsontestsupport.CucumberJSONParser.parse(CucumberJSONParser.java:94)
	at org.jenkinsci.plugins.cucumber.jsontestsupport.CucumberJSONParser.parse(CucumberJSONParser.java:44)
	at org.jenkinsci.plugins.cucumber.jsontestsupport.DefaultTestResultParserImpl$ParseResultCallable.invoke(DefaultTestResultParserImpl.java:161)
	at org.jenkinsci.plugins.cucumber.jsontestsupport.DefaultTestResultParserImpl$ParseResultCallable.invoke(DefaultTestResultParserImpl.java:107)
	at hudson.FilePath.act(FilePath.java:916)
	at hudson.FilePath.act(FilePath.java:889)
	at org.jenkinsci.plugins.cucumber.jsontestsupport.DefaultTestResultParserImpl.parse(DefaultTestResultParserImpl.java:101)
	at org.jenkinsci.plugins.cucumber.jsontestsupport.CucumberJSONParser.parse(CucumberJSONParser.java:116)
	at org.jenkinsci.plugins.cucumber.jsontestsupport.CucumberTestResultArchiver.perform(CucumberTestResultArchiver.java:93)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:754)
	at hudson.model.Build$BuildExecution.post2(Build.java:183)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:707)
	at hudson.model.Run.execute(Run.java:1690)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:46)
	at hudson.model.ResourceController.execute(ResourceController.java:88)
	at hudson.model.Executor.run(Executor.java:246)
[htmlpublisher] Archiving HTML reports...
[htmlpublisher] Archiving at PROJECT level /var/lib/jenkins/workspace/Neo-CLP-Certification-Suite/rivettests/target/CLPGUI/BrokenGUI to /var/lib/jenkins/jobs/Neo-CLP-Certification-Suite/htmlreports/Broken_GUI_Report
[htmlpublisher] Archiving at PROJECT level /var/lib/jenkins/workspace/Neo-CLP-Certification-Suite/rivettests/target/CLPGUI/NormalView to /var/lib/jenkins/jobs/Neo-CLP-Certification-Suite/htmlreports/Normal_View_Report

## My cucumber.json is as follows:
[
  {
    "id": "validate-sanity-of-the-customer-landing-pages",
    "description": "",
    "name": "Validate Sanity of the Customer Landing Pages",
    "keyword": "Feature",
    "line": 1,
    "elements": [
      {
        "id": "validate-sanity-of-the-customer-landing-pages;validate-login,-attend,-ui-for-a-clp",
        "tags": [
          {
            "name": "@rivetclp",
            "line": 597
          }
        ],
        "before": [
          {
            "result": {
              "duration": 4808014250,
              "status": "passed"
            },
            "match": {
              "location": "BrowserInitializer.beforeNonMultiBrowser()"
            }
          }
        ],
        "description": "",
        "name": "Validate Login, Attend, UI for a CLP",
        "keyword": "Scenario Outline",
        "line": 598,
        "steps": [
          {
            "name": "I navigate to the clp for \"\u003cCLP\u003e\"",
            "keyword": "When ",
            "line": 599
          },
          {
            "name": "I capture a screenshot of the clp for \"\u003cCLP\u003e\" in the path \"target/CLPGUI/NormalView/\"",
            "keyword": "Then ",
            "line": 600
          },
          {
            "name": "I login and attend on the clp \"\u003cCLP\u003e\" with invalid input",
            "keyword": "And ",
            "line": 601
          },
          {
            "name": "I capture a screenshot of the clp for \"\u003cCLP\u003e\" in the path \"target/CLPGUI/BrokenGUI/\"",
            "keyword": "Then ",
            "line": 602
          },
          {
            "name": "I verify that attend meeting works fine on the clp",
            "keyword": "Then ",
            "line": 603
          },
          {
            "name": "I navigate to the clp for \"\u003cCLP\u003e\"",
            "keyword": "And ",
            "line": 604
          },
          {
            "name": "I verify that login works fine on the clp",
            "keyword": "Then ",
            "line": 605
          }
        ],
        "examples": [
          {
            "id": "validate-sanity-of-the-customer-landing-pages;validate-login,-attend,-ui-for-a-clp;",
            "description": "Examples:",
            "name": "",
            "keyword": "Examples",
            "line": 606,
            "rows": [
              {
                "id": "validate-sanity-of-the-customer-landing-pages;validate-login,-attend,-ui-for-a-clp;;1",
                "cells": [
                  "CLP"
                ],
                "line": 608
              },
              {
                "id": "validate-sanity-of-the-customer-landing-pages;validate-login,-attend,-ui-for-a-clp;;2",
                "cells": [
                  "rwjf"
                ],
                "line": 609
              },
              {
                "id": "validate-sanity-of-the-customer-landing-pages;validate-login,-attend,-ui-for-a-clp;;3",
                "cells": [
                  "fb"
                ],
                "line": 610
              }
            ]
          }
        ],
        "type": "scenario_outline"
      },
      {
        "after": [
          {
            "result": {
              "duration": 270634483,
              "status": "passed"
            },
            "match": {
              "location": "BrowserInitializer.afterNonMultiBrowser()"
            }
          },
          {
            "result": {
              "duration": 119633,
              "status": "passed"
            },
            "match": {
              "location": "BrowserInitializer.embedScreenshot(Scenario)"
            }
          }
        ],
        "id": "validate-sanity-of-the-customer-landing-pages;validate-login,-attend,-ui-for-a-clp;;2",
        "tags": [
          {
            "name": "@rivetclp",
            "line": 597
          }
        ],
        "before": [
          {
            "result": {
              "duration": 4240605940,
              "status": "passed"
            },
            "match": {
              "location": "BrowserInitializer.beforeNonMultiBrowser()"
            }
          }
        ],
        "description": "",
        "name": "Validate Login, Attend, UI for a CLP",
        "keyword": "Scenario Outline",
        "line": 609,
        "steps": [
          {
            "result": {
              "duration": 5817138190,
              "status": "passed"
            },
            "name": "I navigate to the clp for \"rwjf\"",
            "keyword": "When ",
            "line": 599,
            "match": {
              "arguments": [
                {
                  "val": "rwjf",
                  "offset": 27
                }
              ],
              "location": "ClpSteps.I_navigate_to_the_clp(String)"
            },
            "matchedColumns": [
              0
            ]
          },
          {
            "result": {
              "duration": 515103983,
              "status": "passed"
            },
            "name": "I capture a screenshot of the clp for \"rwjf\" in the path \"target/CLPGUI/NormalView/\"",
            "keyword": "Then ",
            "line": 600,
            "match": {
              "arguments": [
                {
                  "val": "rwjf",
                  "offset": 39
                },
                {
                  "val": "target/CLPGUI/NormalView/",
                  "offset": 58
                }
              ],
              "location": "ClpSteps.I_capture_a_screenshot_of_the_clp(String,String)"
            },
            "matchedColumns": [
              0
            ]
          },
          {
            "result": {
              "duration": 13210578843,
              "status": "passed"
            },
            "name": "I login and attend on the clp \"rwjf\" with invalid input",
            "keyword": "And ",
            "line": 601,
            "match": {
              "arguments": [
                {
                  "val": "rwjf",
                  "offset": 31
                }
              ],
              "location": "ClpSteps.I_login_and_attend_on_the_clp_with_invalid_input(String)"
            },
            "matchedColumns": [
              0
            ]
          },
          {
            "result": {
              "duration": 311440592,
              "status": "passed"
            },
            "name": "I capture a screenshot of the clp for \"rwjf\" in the path \"target/CLPGUI/BrokenGUI/\"",
            "keyword": "Then ",
            "line": 602,
            "match": {
              "arguments": [
                {
                  "val": "rwjf",
                  "offset": 39
                },
                {
                  "val": "target/CLPGUI/BrokenGUI/",
                  "offset": 58
                }
              ],
              "location": "ClpSteps.I_capture_a_screenshot_of_the_clp(String,String)"
            },
            "matchedColumns": [
              0
            ]
          },
          {
            "result": {
              "duration": 15155439292,
              "status": "passed"
            },
            "name": "I verify that attend meeting works fine on the clp",
            "keyword": "Then ",
            "line": 603,
            "match": {
              "location": "ClpSteps.I_verify_that_attend_meeting_works_fine_on_the_clp()"
            }
          },
          {
            "result": {
              "duration": 3142966829,
              "status": "passed"
            },
            "name": "I navigate to the clp for \"rwjf\"",
            "keyword": "And ",
            "line": 604,
            "match": {
              "arguments": [
                {
                  "val": "rwjf",
                  "offset": 27
                }
              ],
              "location": "ClpSteps.I_navigate_to_the_clp(String)"
            },
            "matchedColumns": [
              0
            ]
          },
          {
            "result": {
              "duration": 6420469425,
              "status": "passed"
            },
            "name": "I verify that login works fine on the clp",
            "keyword": "Then ",
            "line": 605,
            "match": {
              "location": "ClpSteps.I_verify_login_functionality_on_the_launched_clp()"
            }
          }
        ],
        "type": "scenario"
      },
      {
        "after": [
          {
            "result": {
              "duration": 251358199,
              "status": "passed"
            },
            "match": {
              "location": "BrowserInitializer.afterNonMultiBrowser()"
            }
          },
          {
            "result": {
              "duration": 41987,
              "status": "passed"
            },
            "match": {
              "location": "BrowserInitializer.embedScreenshot(Scenario)"
            }
          }
        ],
        "id": "validate-sanity-of-the-customer-landing-pages;validate-login,-attend,-ui-for-a-clp;;3",
        "tags": [
          {
            "name": "@rivetclp",
            "line": 597
          }
        ],
        "description": "",
        "name": "Validate Login, Attend, UI for a CLP",
        "keyword": "Scenario Outline",
        "line": 610,
        "steps": [
          {
            "result": {
              "duration": 5372596751,
              "status": "passed"
            },
            "name": "I navigate to the clp for \"fb\"",
            "keyword": "When ",
            "line": 599,
            "match": {
              "arguments": [
                {
                  "val": "fb",
                  "offset": 27
                }
              ],
              "location": "ClpSteps.I_navigate_to_the_clp(String)"
            },
            "matchedColumns": [
              0
            ]
          },
          {
            "result": {
              "duration": 289826787,
              "status": "passed"
            },
            "name": "I capture a screenshot of the clp for \"fb\" in the path \"target/CLPGUI/NormalView/\"",
            "keyword": "Then ",
            "line": 600,
            "match": {
              "arguments": [
                {
                  "val": "fb",
                  "offset": 39
                },
                {
                  "val": "target/CLPGUI/NormalView/",
                  "offset": 56
                }
              ],
              "location": "ClpSteps.I_capture_a_screenshot_of_the_clp(String,String)"
            },
            "matchedColumns": [
              0
            ]
          },
          {
            "result": {
              "duration": 13561892730,
              "status": "passed"
            },
            "name": "I login and attend on the clp \"fb\" with invalid input",
            "keyword": "And ",
            "line": 601,
            "match": {
              "arguments": [
                {
                  "val": "fb",
                  "offset": 31
                }
              ],
              "location": "ClpSteps.I_login_and_attend_on_the_clp_with_invalid_input(String)"
            },
            "matchedColumns": [
              0
            ]
          },
          {
            "result": {
              "duration": 281717530,
              "status": "passed"
            },
            "name": "I capture a screenshot of the clp for \"fb\" in the path \"target/CLPGUI/BrokenGUI/\"",
            "keyword": "Then ",
            "line": 602,
            "match": {
              "arguments": [
                {
                  "val": "fb",
                  "offset": 39
                },
                {
                  "val": "target/CLPGUI/BrokenGUI/",
                  "offset": 56
                }
              ],
              "location": "ClpSteps.I_capture_a_screenshot_of_the_clp(String,String)"
            },
            "matchedColumns": [
              0
            ]
          },
          {
            "result": {
              "duration": 15651178841,
              "status": "passed"
            },
            "name": "I verify that attend meeting works fine on the clp",
            "keyword": "Then ",
            "line": 603,
            "match": {
              "location": "ClpSteps.I_verify_that_attend_meeting_works_fine_on_the_clp()"
            }
          },
          {
            "result": {
              "duration": 3214420578,
              "status": "passed"
            },
            "name": "I navigate to the clp for \"fb\"",
            "keyword": "And ",
            "line": 604,
            "match": {
              "arguments": [
                {
                  "val": "fb",
                  "offset": 27
                }
              ],
              "location": "ClpSteps.I_navigate_to_the_clp(String)"
            },
            "matchedColumns": [
              0
            ]
          },
          {
            "result": {
              "duration": 5581382078,
              "status": "passed"
            },
            "name": "I verify that login works fine on the clp",
            "keyword": "Then ",
            "line": 605,
            "match": {
              "location": "ClpSteps.I_verify_login_functionality_on_the_launched_clp()"
            }
          }
        ],
        "type": "scenario"
      }
    ],
    "uri": "features/meetme/clp/CustomerLandingPages.feature"
  }
]

**Comment by damianszczepanik** [comment]
Full support for undefined phrases (this is above case) will be released with next version.

**Comment by bhavanimagam123** [comment]
Hi,

We are getting parsing errorrs while using report_builder:   report_builder -s reports
INPUT is["reports/results.json", "reports/results2.json"]
RuntimeError: ReportBuilderParsingError



Here is out json file:


[
  {
    "id": "general-non-service-specific-tests-for-content-ott-api",
    "tags": [
      {
        "name": "@content_ott_navigation_general",
        "line": 1
      },
      {
        "name": "@headless",
        "line": 1
      }
    ],
    "description": "",
    "name": "General non-service specific tests for content_ott API",
    "keyword": "Feature",
    "line": 2,
    "elements": [
      {
        "id": "general-non-service-specific-tests-for-content-ott-api;cache-behaviour-for-app-nav-feeds",
        "tags": [
          {
            "name": "@MP-245",
            "line": 247
          },
          {
            "name": "@MP-449",
            "line": 247
          },
          {
            "name": "@MP-574",
            "line": 247
          },
          {
            "name": "@bhavani_new",
            "line": 247
          }
        ],
        "description": "",
        "name": "Cache behaviour for app nav feeds",
        "keyword": "Scenario Outline",
        "line": 248,
        "steps": [
          {
            "name": "I flush catalogue feeds cache",
            "keyword": "Given ",
            "line": 249,
            "match": {
              "location": "features/step_definitions/feeds/content_ott_general_steps.rb:50"
            }
          },
          {
            "name": "I am using device \u003cdevice\u003e on site \u003csite\u003e",
            "keyword": "And ",
            "line": 250,
            "match": {
              "arguments": [
                {
                  "val": "android",
                  "offset": 18
                },
                {
                  "val": "goan",
                  "offset": 34
                }
              ],
              "location": "features/step_definitions/feeds/content_ott_general_steps.rb:58"
            }
          },
          {
            "name": "I call the Content OTT feed for version \u003cversion\u003e for the following pages",
            "keyword": "And ",
            "line": 251,
            "match": {
              "arguments": [
                {
                  "val": "v2",
                  "offset": 40
                },
                {
                  "val": "pages",
                  "offset": 61
                }
              ],
              "location": "features/step_definitions/feeds/content_ott_general_steps.rb:14"
            },
            "rows": [
              {
                "cells": [
                  "Application Navigation"
                ],
                "line": 252
              },
              {
                "cells": [
                  "Promo Page"
                ],
                "line": 253
              },
              {
                "cells": [
                  "AtoZ Page"
                ],
                "line": 254
              },
              {
                "cells": [
                  "Linear Streams"
                ],
                "line": 255
              }
            ]
          },
          {
            "name": "I store the header values sent by cache",
            "keyword": "And ",
            "line": 256,
            "match": {
              "location": "features/step_definitions/feeds/content_ott_general_steps.rb:34"
            }
          },
          {
            "name": "I call the same Content OTT application navigation feeds for version \u003cversion\u003e",
            "keyword": "When ",
            "line": 257,
            "match": {
              "arguments": [
                {
                  "val": "application navigation",
                  "offset": 28
                },
                {
                  "val": "v2",
                  "offset": 69
                },
                {}
              ],
              "location": "features/step_definitions/feeds/content_ott_general_steps.rb:26"
            }
          },
          {
            "name": "the header values sent by cache should not have changed",
            "keyword": "Then ",
            "line": 258,
            "match": {
              "arguments": [
                {
                  "val": "should not",
                  "offset": 32
                }
              ],
              "location": "features/step_definitions/feeds/content_ott_general_steps.rb:38"
            }
          },
          {
            "name": "I flush catalogue feeds cache",
            "keyword": "And ",
            "line": 259,
            "match": {
              "location": "features/step_definitions/feeds/content_ott_general_steps.rb:50"
            }
          },
          {
            "name": "I call the same Content OTT application navigation feeds for version \u003cversion\u003e",
            "keyword": "And ",
            "line": 260,
            "match": {
              "arguments": [
                {
                  "val": "application navigation",
                  "offset": 28
                },
                {
                  "val": "v2",
                  "offset": 69
                },
                {}
              ],
              "location": "features/step_definitions/feeds/content_ott_general_steps.rb:26"
            }
          },
          {
            "name": "the header values sent by cache should have changed",
            "keyword": "Then ",
            "line": 261,
            "match": {
              "arguments": [
                {
                  "val": "should",
                  "offset": 32
                }
              ],
              "location": "features/step_definitions/feeds/content_ott_general_steps.rb:38"
            }
          }
        ],
        "examples": [
          {
            "id": "general-non-service-specific-tests-for-content-ott-api;cache-behaviour-for-app-nav-feeds;",
            "description": "",
            "name": "",
            "keyword": "Examples",
            "line": 262,
            "rows": [
              {
                "id": "general-non-service-specific-tests-for-content-ott-api;cache-behaviour-for-app-nav-feeds;;1",
                "cells": [
                  "site",
                  "device",
                  "version"
                ],
                "line": 263
              },
              {
                "id": "general-non-service-specific-tests-for-content-ott-api;cache-behaviour-for-app-nav-feeds;;2",
                "cells": [
                  "goan",
                  "android",
                  "v2"
                ],
                "line": 264
              },
              {
                "id": "general-non-service-specific-tests-for-content-ott-api;cache-behaviour-for-app-nav-feeds;;4",
                "cells": [
                  "goio",
                  "ios",
                  "v2"
                ],
                "line": 266
              },
              {
                "id": "general-non-service-specific-tests-for-content-ott-api;cache-behaviour-for-app-nav-feeds;;6",
                "cells": [
                  "gowb",
                  "pc",
                  "v2"
                ],
                "line": 268
              }
            ]
          }
        ],
        "type": "scenario_outline"
      },
      {
        "id": "general-non-service-specific-tests-for-content-ott-api;invalid-servlet-in-the-content-ott-url-should-return-error-in-json-format-if-accept-header-from-client-is-json",
        "tags": [
          {
            "name": "@MP-432",
            "line": 526
          },
          {
            "name": "@bhavani_new",
            "line": 526
          }
        ],
        "description": "",
        "name": "Invalid servlet in the Content OTT url should return error in JSON format if Accept header from client is json",
        "keyword": "Scenario Outline",
        "line": 527,
        "steps": [
          {
            "name": "I flush catalogue feeds cache",
            "keyword": "Given ",
            "line": 528,
            "match": {
              "location": "features/step_definitions/feeds/content_ott_general_steps.rb:50"
            }
          },
          {
            "name": "I am using device \u003cdevice\u003e on site \u003csite\u003e",
            "keyword": "And ",
            "line": 529,
            "match": {
              "arguments": [
                {
                  "val": "android",
                  "offset": 18
                },
                {
                  "val": "goan",
                  "offset": 34
                }
              ],
              "location": "features/step_definitions/feeds/content_ott_general_steps.rb:58"
            }
          },
          {
            "name": "I call the OTT Content Device feed for version \u003cversion\u003e with the \u0027catalogue\u0027 component in the url",
            "keyword": "When ",
            "line": 530,
            "match": {
              "arguments": [
                {
                  "val": "v2",
                  "offset": 47
                }
              ],
              "location": "features/step_definitions/feeds/content_ott_general_steps.rb:102"
            }
          },
          {
            "name": "I should see error Error Code(404) in the response",
            "keyword": "Then ",
            "line": 531,
            "match": {
              "arguments": [
                {
                  "val": "Error Code(404)",
                  "offset": 19
                }
              ],
              "location": "features/step_definitions/common/rest_service_steps.rb:18"
            }
          }
        ],
        "examples": [
          {
            "id": "general-non-service-specific-tests-for-content-ott-api;invalid-servlet-in-the-content-ott-url-should-return-error-in-json-format-if-accept-header-from-client-is-json;",
            "description": "",
            "name": "",
            "keyword": "Examples",
            "line": 532,
            "rows": [
              {
                "id": "general-non-service-specific-tests-for-content-ott-api;invalid-servlet-in-the-content-ott-url-should-return-error-in-json-format-if-accept-header-from-client-is-json;;1",
                "cells": [
                  "site",
                  "device",
                  "version"
                ],
                "line": 533
              },
              {
                "id": "general-non-service-specific-tests-for-content-ott-api;invalid-servlet-in-the-content-ott-url-should-return-error-in-json-format-if-accept-header-from-client-is-json;;2",
                "cells": [
                  "goan",
                  "android",
                  "v2"
                ],
                "line": 534
              },
              {
                "id": "general-non-service-specific-tests-for-content-ott-api;invalid-servlet-in-the-content-ott-url-should-return-error-in-json-format-if-accept-header-from-client-is-json;;4",
                "cells": [
                  "goio",
                  "ios",
                  "v2"
                ],
                "line": 536
              },
              {
                "id": "general-non-service-specific-tests-for-content-ott-api;invalid-servlet-in-the-content-ott-url-should-return-error-in-json-format-if-accept-header-from-client-is-json;;6",
                "cells": [
                  "gowb",
                  "pc",
                  "v2"
                ],
                "line": 538
              }
            ]
          }
        ],
        "type": "scenario_outline"
      }
    ],
    "uri": "features/feeds/json/content_ott_general.feature"
  }
]






Jsonfile2: 




[
  {
    "id": "general-non-service-specific-tests-for-content-ott-api",
    "tags": [
      {
        "name": "@content_ott_navigation_general",
        "line": 1
      },
      {
        "name": "@headless",
        "line": 1
      }
    ],
    "description": "",
    "name": "General non-service specific tests for content_ott API",
    "keyword": "Feature",
    "line": 2,
    "elements": [
      {
        "id": "general-non-service-specific-tests-for-content-ott-api;responses-to-/protected/-calls-should-have-expires-header-and-no-cache-control-header",
        "tags": [
          {
            "name": "@MP-2175",
            "line": 160
          },
          {
            "name": "@bhavani_new",
            "line": 160
          }
        ],
        "description": "",
        "name": "Responses to /protected/ calls should have expires header and no cache-control header",
        "keyword": "Scenario",
        "line": 161,
        "steps": [
          {
            "result": {
              "status": "failed",
              "error_message": "Response should be 200. Got 403 for service /protected/clear-cache  (RSpec::Expectations::ExpectationNotMetError)\n./lib/ott/test/catfeeds/steps/general.rb:626:in `call_various_catFeeds_protected_endpoints\u0027\norg/jruby/RubyHash.java:1337:in `each\u0027\n./lib/ott/test/catfeeds/steps/general.rb:622:in `call_various_catFeeds_protected_endpoints\u0027\n./features/step_definitions/feeds/content_ott_general_steps.rb:292:in `/^I call all the CatFeeds protected endpoints$/\u0027\nfeatures/feeds/json/content_ott_general.feature:162:in `Given I call all the CatFeeds protected endpoints\u0027"
            },
            "name": "I call all the CatFeeds protected endpoints",
            "keyword": "Given ",
            "line": 162,
            "match": {
              "location": "features/step_definitions/feeds/content_ott_general_steps.rb:291"
            }
          },
          {
            "result": {
              "status": "skipped"
            },
            "name": "header expires value is lesser than 1 second from the date header",
            "keyword": "Then ",
            "line": 163,
            "match": {
              "arguments": [
                {
                  "val": "lesser",
                  "offset": 24
                },
                {
                  "val": "1",
                  "offset": 36
                }
              ],
              "location": "features/step_definitions/feeds/content_ott_general_steps.rb:238"
            }
          },
          {
            "result": {
              "status": "skipped"
            },
            "name": "the cache-control header should not be present in the response header",
            "keyword": "Then ",
            "line": 164,
            "match": {
              "arguments": [
                {
                  "val": "cache-control",
                  "offset": 4
                }
              ],
              "location": "features/step_definitions/feeds/content_ott_general_steps.rb:226"
            }
          }
        ],
        "type": "scenario"
      },
      {
        "id": "general-non-service-specific-tests-for-content-ott-api;cache-behaviour-for-app-nav-feeds",
        "tags": [
          {
            "name": "@MP-245",
            "line": 247
          },
          {
            "name": "@MP-449",
            "line": 247
          },
          {
            "name": "@MP-574",
            "line": 247
          },
          {
            "name": "@bhavani_new",
            "line": 247
          }
        ],
        "description": "",
        "name": "Cache behaviour for app nav feeds",
        "keyword": "Scenario Outline",
        "line": 248,
        "steps": [
          {
            "name": "I flush catalogue feeds cache",
            "keyword": "Given ",
            "line": 249,
            "match": {
              "location": "features/step_definitions/feeds/content_ott_general_steps.rb:50"
            }
          },
          {
            "name": "I am using device \u003cdevice\u003e on site \u003csite\u003e",
            "keyword": "And ",
            "line": 250,
            "match": {
              "arguments": [
                {
                  "val": "kids",
                  "offset": 18
                },
                {
                  "val": "goan",
                  "offset": 31
                }
              ],
              "location": "features/step_definitions/feeds/content_ott_general_steps.rb:58"
            }
          },
          {
            "name": "I call the Content OTT feed for version \u003cversion\u003e for the following pages",
            "keyword": "And ",
            "line": 251,
            "match": {
              "arguments": [
                {
                  "val": "v2",
                  "offset": 40
                },
                {
                  "val": "pages",
                  "offset": 61
                }
              ],
              "location": "features/step_definitions/feeds/content_ott_general_steps.rb:14"
            },
            "rows": [
              {
                "cells": [
                  "Application Navigation"
                ],
                "line": 252
              },
              {
                "cells": [
                  "Promo Page"
                ],
                "line": 253
              },
              {
                "cells": [
                  "AtoZ Page"
                ],
                "line": 254
              },
              {
                "cells": [
                  "Linear Streams"
                ],
                "line": 255
              }
            ]
          },
          {
            "name": "I store the header values sent by cache",
            "keyword": "And ",
            "line": 256,
            "match": {
              "location": "features/step_definitions/feeds/content_ott_general_steps.rb:34"
            }
          },
          {
            "name": "I call the same Content OTT application navigation feeds for version \u003cversion\u003e",
            "keyword": "When ",
            "line": 257,
            "match": {
              "arguments": [
                {
                  "val": "application navigation",
                  "offset": 28
                },
                {
                  "val": "v2",
                  "offset": 69
                },
                {}
              ],
              "location": "features/step_definitions/feeds/content_ott_general_steps.rb:26"
            }
          },
          {
            "name": "the header values sent by cache should not have changed",
            "keyword": "Then ",
            "line": 258,
            "match": {
              "arguments": [
                {
                  "val": "should not",
                  "offset": 32
                }
              ],
              "location": "features/step_definitions/feeds/content_ott_general_steps.rb:38"
            }
          },
          {
            "name": "I flush catalogue feeds cache",
            "keyword": "And ",
            "line": 259,
            "match": {
              "location": "features/step_definitions/feeds/content_ott_general_steps.rb:50"
            }
          },
          {
            "name": "I call the same Content OTT application navigation feeds for version \u003cversion\u003e",
            "keyword": "And ",
            "line": 260,
            "match": {
              "arguments": [
                {
                  "val": "application navigation",
                  "offset": 28
                },
                {
                  "val": "v2",
                  "offset": 69
                },
                {}
              ],
              "location": "features/step_definitions/feeds/content_ott_general_steps.rb:26"
            }
          },
          {
            "name": "the header values sent by cache should have changed",
            "keyword": "Then ",
            "line": 261,
            "match": {
              "arguments": [
                {
                  "val": "should",
                  "offset": 32
                }
              ],
              "location": "features/step_definitions/feeds/content_ott_general_steps.rb:38"
            }
          }
        ],
        "examples": [
          {
            "id": "general-non-service-specific-tests-for-content-ott-api;cache-behaviour-for-app-nav-feeds;",
            "description": "",
            "name": "",
            "keyword": "Examples",
            "line": 262,
            "rows": [
              {
                "id": "general-non-service-specific-tests-for-content-ott-api;cache-behaviour-for-app-nav-feeds;;1",
                "cells": [
                  "site",
                  "device",
                  "version"
                ],
                "line": 263
              },
              {
                "id": "general-non-service-specific-tests-for-content-ott-api;cache-behaviour-for-app-nav-feeds;;3",
                "cells": [
                  "goan",
                  "kids",
                  "v2"
                ],
                "line": 265
              },
              {
                "id": "general-non-service-specific-tests-for-content-ott-api;cache-behaviour-for-app-nav-feeds;;5",
                "cells": [
                  "gops",
                  "ps",
                  "v2"
                ],
                "line": 267
              },
              {
                "id": "general-non-service-specific-tests-for-content-ott-api;cache-behaviour-for-app-nav-feeds;;7",
                "cells": [
                  "goxb",
                  "xbox",
                  "v3"
                ],
                "line": 269
              }
            ]
          }
        ],
        "type": "scenario_outline"
      },
      {
        "id": "general-non-service-specific-tests-for-content-ott-api;invalid-servlet-in-the-content-ott-url-should-return-error-in-json-format-if-accept-header-from-client-is-json",
        "tags": [
          {
            "name": "@MP-432",
            "line": 526
          },
          {
            "name": "@bhavani_new",
            "line": 526
          }
        ],
        "description": "",
        "name": "Invalid servlet in the Content OTT url should return error in JSON format if Accept header from client is json",
        "keyword": "Scenario Outline",
        "line": 527,
        "steps": [
          {
            "name": "I flush catalogue feeds cache",
            "keyword": "Given ",
            "line": 528,
            "match": {
              "location": "features/step_definitions/feeds/content_ott_general_steps.rb:50"
            }
          },
          {
            "name": "I am using device \u003cdevice\u003e on site \u003csite\u003e",
            "keyword": "And ",
            "line": 529,
            "match": {
              "arguments": [
                {
                  "val": "kids",
                  "offset": 18
                },
                {
                  "val": "goan",
                  "offset": 31
                }
              ],
              "location": "features/step_definitions/feeds/content_ott_general_steps.rb:58"
            }
          },
          {
            "name": "I call the OTT Content Device feed for version \u003cversion\u003e with the \u0027catalogue\u0027 component in the url",
            "keyword": "When ",
            "line": 530,
            "match": {
              "arguments": [
                {
                  "val": "v2",
                  "offset": 47
                }
              ],
              "location": "features/step_definitions/feeds/content_ott_general_steps.rb:102"
            }
          },
          {
            "name": "I should see error Error Code(404) in the response",
            "keyword": "Then ",
            "line": 531,
            "match": {
              "arguments": [
                {
                  "val": "Error Code(404)",
                  "offset": 19
                }
              ],
              "location": "features/step_definitions/common/rest_service_steps.rb:18"
            }
          }
        ],
        "examples": [
          {
            "id": "general-non-service-specific-tests-for-content-ott-api;invalid-servlet-in-the-content-ott-url-should-return-error-in-json-format-if-accept-header-from-client-is-json;",
            "description": "",
            "name": "",
            "keyword": "Examples",
            "line": 532,
            "rows": [
              {
                "id": "general-non-service-specific-tests-for-content-ott-api;invalid-servlet-in-the-content-ott-url-should-return-error-in-json-format-if-accept-header-from-client-is-json;;1",
                "cells": [
                  "site",
                  "device",
                  "version"
                ],
                "line": 533
              },
              {
                "id": "general-non-service-specific-tests-for-content-ott-api;invalid-servlet-in-the-content-ott-url-should-return-error-in-json-format-if-accept-header-from-client-is-json;;3",
                "cells": [
                  "goan",
                  "kids",
                  "v2"
                ],
                "line": 535
              },
              {
                "id": "general-non-service-specific-tests-for-content-ott-api;invalid-servlet-in-the-content-ott-url-should-return-error-in-json-format-if-accept-header-from-client-is-json;;5",
                "cells": [
                  "gops",
                  "ps",
                  "v2"
                ],
                "line": 537
              },
              {
                "id": "general-non-service-specific-tests-for-content-ott-api;invalid-servlet-in-the-content-ott-url-should-return-error-in-json-format-if-accept-header-from-client-is-json;;7",
                "cells": [
                  "goxb",
                  "xbox",
                  "v3"
                ],
                "line": 539
              }
            ]
          }
        ],
        "type": "scenario_outline"
      }
    ],
    "uri": "features/feeds/json/content_ott_general.feature"
  }
]
