### ISSUE TITLE
"Result was missing for this step" for scenario outline

### ISSUE THREAD

**Issue by gabyshev** [damianszczepanik/cucumber-reporting-jenkins#96]
Reports don't correctly show the steps from Scenario Outline:
![cucumber jvm html reports feature](https://cloud.githubusercontent.com/assets/2675242/2913752/ccb25dd6-d690-11e3-9553-efacaf6ee8c9.png)

**Comment by damianszczepanik** [comment]
damianszczepanik/cucumber-reporting/pull/62 is closed
