### ISSUE TITLE
When running parallel tests in Jenkins over multiple devices, only the latest feature report is available.

### ISSUE THREAD

**Issue by mathias21** [damianszczepanik/cucumber-reporting-jenkins#99]
After setting Jenkins to run a script to test same feature files over multiple devices, the generated feature reports are using the same name, so only the latest one is surviving. So you can see the different report rows inside the Cucumber Report, but when you try to access to the detailed html per feature, you always see the same one.

The problem comes from ReportBuilder in Cucumber-Reporting library. It is indexing using the feature name. It was not expected to have more than one device at the same time generating Jsons with the same feature.

![screen shot 2014-06-12 at 16 13 15](https://cloud.githubusercontent.com/assets/7766710/3258696/15f8c810-f23c-11e3-8479-0139b766da57.png)

**Comment by nick-haworth** [comment]
@mathias21 @kingsleyh Is this working? Currently I am trying to display parallel reports on jenkins, I have installed cucumber-reports-0.0.24 and selected the parallel testing box. When running cucumber the json files are getting created, eg ie-8-windows-7_report_.json but when I look at the cucumber reports it is just one report with all the features mutliplied by how many browsers I ran and there is no way of knowing when feature links to which browser.

**Comment by mathias21** [comment]
Hi @nick-haworth 
Not sure about the state of master @kingsleyh. 
In my repo, you should set the parallel variable to true or use it within the jenkins plugin I modified, also merged with @kingsleyh master.
If you are using ReportBuilder, then you can use this Constructor:

    public ReportBuilder(List<String> jsonReports, File reportDirectory, String pluginUrlPath, String buildNumber, String buildProject, boolean skippedFails, boolean undefinedFails, boolean flashCharts, boolean runWithJenkins, boolean artifactsEnabled, String artifactConfig, boolean highCharts, boolean parallelTesting) throws Exception;

and set the latest boolean parameter (parallelTesting) to true.

**Comment by kingsleyh** [comment]
I probably just merged into master with it disabled - maybe it needs a config checkbox  in the options so it can be enabled from the Jenkins plugin if desired

**Comment by mathias21** [comment]
@kingsleyh I also modified the jenkins-cucumber-jvm-reports-plugin-java to setup this. A new checkbox is added there to select parallel testing or not. If I remind correctly, already merged with your master.

**Comment by kingsleyh** [comment]
Ok should be in the latest release then unless it's disabled - I vaguely remember it being disabled

**Comment by saikrishna321** [comment]
@kingsleyh  has this been merged with master for handling parallel json files?

**Comment by kingsleyh** [comment]
I think so

**Comment by damianszczepanik** [comment]
Such issues have been recently fixed by big refactor in version 1.00
